First, move within a simulation directory. This directory should contains the sub-directory 'output/' that contains snapshot files, and a file 'snapshot_times.txt' that lists the scale-factors, redshifts, times, and indices of all snapshots stored from the simulation.

Ensure that gizmo_analysis and utilities directories are in your python path, then...

In [1]:
import gizmo_analysis as gizmo
import utilities as ut

import numpy as np

In [2]:
# you can access the files as named or use the aliases in __init__.py to keep it shorter 
# for example, these are the same:

gizmo.gizmo_io
gizmo.io

<module 'gizmo_analysis.gizmo_io' from '/Users/awetzel/work/research/analysis/gizmo_analysis/gizmo_io.py'>

# read particle data

In [3]:
# read star and dark-matter particles at z = 0

part = gizmo.io.Read.read_snapshots(['star', 'dark'], 'redshift', 0)


# in utilities.simulation.Snapshot():
* reading:  snapshot_times.txt

* input redshift = 0:  using snapshot index = 600, redshift = 0.000


# in gizmo_analysis.gizmo_io.Read():
* reading header from:  output/snapshot_600.hdf5
  snapshot contains the following number of particles:
    dark      (id = 1): 8820344 particles
    dark2     (id = 2): 3081337 particles
    gas       (id = 0): 5969934 particles
    star      (id = 4): 3059250 particles
    blackhole (id = 5): 0 particles

* reading species: ['star', 'dark']
* reading particles from:
    output/snapshot_600.hdf5

* reading cosmological parameters from:  initial_condition/ic_agora_m12i.conf

* checking sanity of particle properties

* assigning coordinates for 1 host galaxy/halo[s]:
  position = (41821.974, 44122.005, 46288.448) [kpc comoving]
  velocity = (-48.7, 73.2, 96.7) [km / s]



In [4]:
# alternately, read all particle species at z = 0

part = gizmo.io.Read.read_snapshots('all', 'redshift', 0)


# in utilities.simulation.Snapshot():
* reading:  snapshot_times.txt

* input redshift = 0:  using snapshot index = 600, redshift = 0.000


# in gizmo_analysis.gizmo_io.Read():
* reading header from:  output/snapshot_600.hdf5
  snapshot contains the following number of particles:
    dark      (id = 1): 8820344 particles
    dark2     (id = 2): 3081337 particles
    gas       (id = 0): 5969934 particles
    star      (id = 4): 3059250 particles
    blackhole (id = 5): 0 particles

* reading species: ['dark', 'dark2', 'gas', 'star']
* reading particles from:
    output/snapshot_600.hdf5

* reading cosmological parameters from:  initial_condition/ic_agora_m12i.conf

* checking sanity of particle properties

* assigning coordinates for 1 host galaxy/halo[s]:
  position = (41821.974, 44122.005, 46288.448) [kpc comoving]
  velocity = (-48.7, 73.2, 96.7) [km / s]



In [ ]:
# this tutorial assumes that you are in the root directory of a simulation, 
# but you can read a simulation at any location using input argument 'simulation_directory'

part = gizmo.io.Read.read_snapshots('all', 'redshift', 0, simulation_directory='/arb/it/rary/loc/a/tion')

In [ ]:
# each particle species is stored as its own dictionary
# 'star' = stars, 'gas' = gas, 'dark' = dark matter,
# 'dark2', 'dark3', 'dark4', etc = low-resolution dark matter (but you rarely will be interested in this)

part.keys()

In [ ]:
# properties of star particles are stored via dictionary

part['star'].keys()

In [ ]:
# properties of dark-matter particles

part['dark'].keys()

In [ ]:
# properties of gas particles

part['gas'].keys()

# particle properties

In [ ]:
# 3-D position of star particle (particle number x dimension number) [kpc comoving]

part['star']['position']

In [ ]:
# 3-D velocity of star particle (particle number x dimension number) [km / s]

part['star']['velocity']

In [ ]:
# mass of star particle [Msun]

part['star']['mass']

In [ ]:
# formation scale-factor of star particle

part['star']['form.scalefactor']

In [5]:
# use .prop() to compute derived quantities,
# such as the time [Gyr] when a star particle formed
# see gizmo.io.ParticleDictionaryClass for all options for derived quantities

part['star'].prop('form.time')

array([ 5.38456731,  7.35609019,  5.37457175, ..., 10.46071958,
        4.55585177,  3.20527164])

In [6]:
# similarly, get the age of a star particle (the lookback time to when it formed) [Gyr]

part['star'].prop('age')

array([ 8.41417957,  6.44265669,  8.42417513, ...,  3.3380273 ,
        9.24289511, 10.59347525])

In [8]:
# get the mass of a star particle when it formed [Msun], using the stellar evolution tracks in Gizmo

part['star'].prop('form.mass')

array([98218.07407055, 70719.46698618, 57860.98445673, ...,
       57814.24812811, 55872.96596205, 54849.83031645])

# elemental abundances / metallicities

In [ ]:
# elemental abundance is stored in the catalog as linear *mass fraction*
# one value for each element, in a array (particle_number x element number)
# the first value is the mass fraction of all metals (everything not H, He)
# then He, C, N, O, etc

part['star']['massfraction']

In [ ]:
# get individual elements by their index

# total metal mass fraction (everything not H, He) is index 0
print(part['star']['massfraction'][:, 0])

# iron is index 10
print(part['star']['massfraction'][:, 10])

In [ ]:
# alternately use .prop() to compute derived quantities,
# including calling element by its name or symbol
# see gizmo.io.ParticleDictionaryClass for all options for derived quantities

print(part['star'].prop('massfraction.metals'))
print(part['star'].prop('massfraction.carbon'))
print(part['star'].prop('massfraction.iron'))
print(part['star'].prop('massfraction.fe'))  # can use name or symbol

In [ ]:
# also use .prop() to compute metallicity [Z / H]
# for example, iron abundance [Fe / H] :=
#   log10((mass_iron / mass_hydrogen)_particle / (mass_iron / mass_hydrogen)_sun)
# my pipeline assumes solar abundances from Asplund et al 2009

print(part['star'].prop('metallicity.total'))
print(part['star'].prop('metallicity.fe'))

In [ ]:
# also use .prop() to compute simple arithmetic combinations, such as [Mg / Fe]

part['star'].prop('metallicity.mg - metallicity.fe')

In [ ]:
# refer to utilities.basic.constant for assumed solar values (Asplund et al 2009) and other constants

ut.constant.sun_composition

# meta-data about simulation

In [ ]:
# dictionary of useful information about the simulation

part.info

In [ ]:
# dictionary of information about this snapshot's index, scale-factor, redshift, time, lookback-time

part.snapshot

In [ ]:
# dictionary class with information about *all* snapshots that were saved for the simulation

print(part.Snapshot.keys())
print(part.Snapshot['redshift'][:10])

In [ ]:
# dictionary class of cosmological parameters, with internal functions for cosmological conversions
# see utilities.cosmology for more on this

part.Cosmology

See gizmo.analysis for examples of high-level analysis, including plotting these data.

See ut.particle for mid-level analysis functions that may be useful.

See other modules within utilities for low-level functions that may be useful.

# coordinates of host galaxy/halo and principal axes of stellar disk

If you enable read_snapshots(assign_host_coordinates=True) (which is True by default), then during read-in the code assigns the position and velocity of the host galaxy/halo (using stars for a baryonic simulations and dark matter for a DM-only simulation). The code stores these coordinates in arrays appended to the particle catalog.

Most simulations have a single host galaxy/halo, but some (like ELVIS) contain two (or more). You can control the number of hosts via: read_snapshots(host_number=2) (by deafult, host_number=1).

Once the code assigns the coordinates of each host, it also can compute the principal axes (rotation tensor) of each host's stellar disk. Enable this via: read_snapshots(assign_host_principal_axes=True) (by default, assign_host_principal_axes=False).

In [9]:
# position [kpc comoving] and velocity [km / s] of the center of each host galaxy
# can store multiple hosts, though usually just one

print(part.host_positions)
print(part.host_velocities)

[[41821.97367711 44122.00484177 46288.4484585 ]]
[[-48.737286  73.20827   96.66946 ]]


In [10]:
# compute and assign principal axes (defined via moment of inertia tensor) of stars during read in as below

part = gizmo.io.Read.read_snapshots(['star', 'dark'], 'redshift', 0, assign_host_principal_axes=True)


# in utilities.simulation.Snapshot():
* reading:  snapshot_times.txt

* input redshift = 0:  using snapshot index = 600, redshift = 0.000


# in gizmo_analysis.gizmo_io.Read():
* reading header from:  output/snapshot_600.hdf5
  snapshot contains the following number of particles:
    dark      (id = 1): 8820344 particles
    dark2     (id = 2): 3081337 particles
    gas       (id = 0): 5969934 particles
    star      (id = 4): 3059250 particles
    blackhole (id = 5): 0 particles

* reading species: ['star', 'dark']
* reading particles from:
    output/snapshot_600.hdf5

* reading cosmological parameters from:  initial_condition/ic_agora_m12i.conf

* checking sanity of particle properties

* assigning coordinates for 1 host galaxy/halo[s]:
  position = (41821.974, 44122.005, 46288.448) [kpc comoving]
  velocity = (-48.7, 73.2, 96.7) [km / s]

* assigning principal axes of host galaxy[s]/halo[s]:
  using star particles at distance < 15 kpc
  using distance that encloses 90% of mass
  u

In [11]:
# rotation tensor[s] of the principal axes for each host are stored via

print(part.host_rotation_tensors[0])

[[ 0.20397335  0.45612521  0.86622437]
 [ 0.8729429   0.31577278 -0.37183093]
 [-0.44313154  0.83200802 -0.33376204]]


In [12]:
# now you can compute different types of distance of star particles from the center of each host galaxy
# compute 3-D distance from the host center along simulation's default x,y,z cartesian axes [kpc physical]

part['star'].prop('host.distance')

array([[ 1268.83208172,  5564.34890325, -4928.10562341],
       [ 3106.31973213,  2376.85209351, -4314.64238128],
       [ 2343.09614995,  1783.56843904,   860.76900457],
       ...,
       [  137.22019795, -1574.3404895 ,  -179.61490314],
       [  137.33256157, -1574.5766965 ,  -179.46876353],
       [  137.33369847, -1574.91948576,  -179.89308991]])

In [13]:
# add 'total' to compute total (scalar) distance [kpc physical]

part['star'].prop('host.distance.total')

array([7540.43358198, 5823.640359  , 3067.92099375, ..., 1590.48384872,
       1590.71086081, 1591.09819155])

In [14]:
# add 'principal' to compute 3-D distance aligned with the principal (major, intermediate, minor) axes of the host [kpc physical]

part['star'].prop('host.distance.principal')

array([[-1471.99745052,  4697.1099597 ,  5712.13796546],
       [-2019.69978771,  5066.5024369 ,  2041.11559089],
       [ 2037.07879133,  2288.53098007,   158.35142894],
       ...,
       [ -845.6939332 ,  -310.56209532, -1310.72187337],
       [ -845.65216429,  -310.59293526, -1311.01696721],
       [ -846.17584907,  -310.54240865, -1311.16105038]])

In [15]:
# add 'cylindrical' to compute 3-D distance aligned with the principal axes in cylindrical coordinates
# first value is along the major axes (R, positive definite)
# second value is vertical height wrt the disk (Z, signed)
# third value is angle (phi, 0 to 2 * pi)

part['star'].prop('host.distance.principal.cylindrical')

array([[ 4.92235903e+03,  5.71213797e+03,  1.87448602e+00],
       [ 5.45423085e+03,  2.04111559e+03,  1.95012791e+00],
       [ 3.06383160e+03,  1.58351429e+02,  8.43463855e-01],
       ...,
       [ 9.00914560e+02, -1.31072187e+03,  3.49353175e+00],
       [ 9.00885983e+02, -1.31101697e+03,  3.49357987e+00],
       [ 9.01360169e+02, -1.31116105e+03,  3.49332695e+00]])

In [16]:
# same for velocity
# compute 3-D velocity from host galaxy center along simulation's default x,y,z cartesian axes [km / s]

part['star'].prop('host.velocity')

array([[ 153.69781  ,  682.3818   , -596.6675   ],
       [ 439.40842  ,  148.70575  , -766.1859   ],
       [ 339.27658  ,   43.9933   ,   84.86846  ],
       ...,
       [   3.8416476,  -90.69804  , -134.58772  ],
       [   6.3950295, -152.07191  , -133.20901  ],
       [ -22.332697 ,  -87.4856   , -117.72802  ]], dtype=float32)

In [17]:
# compute total (scalar) velocity [km / s]

part['star'].prop('host.velocity.total')

array([919.3911 , 895.6752 , 352.48642, ..., 162.34145, 202.26569,
       148.36565], dtype=float32)

In [18]:
# compute 3-D velocity along the principal (major, intermediate, minor) axes [km / s]

part['star'].prop('host.velocity.principal')

array([[-174.24612  ,  571.5064   ,  698.7837   ],
       [-506.23285  ,  715.4273   ,  184.73242  ],
       [ 162.78496  ,  278.50424  , -142.06725  ],
       ...,
       [-157.16924  ,   24.757446 ,  -32.243576 ],
       [-183.44832  ,    7.0935564,  -84.89878  ],
       [-146.43854  ,   -3.3458223,  -23.599258 ]], dtype=float32)

In [19]:
# compute 3-D velocity in cylindrical coordinates
# first value is along the major axes (positive definite)
# second value is vertical velocity wrt the disk (signed)
# third value is azimuthal velocity in the plane of the disk (positive definite)

part['star'].prop('host.velocity.principal.cylindrical')

array([[ 597.4611   ,  698.7837   ,   -4.6324883],
       [ 852.0271   ,  184.73242  ,  205.32347  ],
       [ 316.2613   , -142.06725  ,   63.57943  ],
       ...,
       [ 139.00136  ,  -32.243576 ,  -77.419136 ],
       [ 169.7554   ,  -84.89878  ,  -69.905    ],
       [ 138.6258   ,  -23.599258 ,  -47.310966 ]], dtype=float32)

In [20]:
# if you want to store multiple hosts (such as for the ELVIS LG-like paired simulations), 
# set host_number=2 during read-in
# (you can do this for any simulation, it simply finds the second most massive host halo in the zoom-in region)

part = gizmo.io.Read.read_snapshots(['star', 'dark'], 'redshift', 0, host_number=2, assign_host_principal_axes=True)


# in utilities.simulation.Snapshot():
* reading:  snapshot_times.txt

* input redshift = 0:  using snapshot index = 600, redshift = 0.000


# in gizmo_analysis.gizmo_io.Read():
* reading header from:  output/snapshot_600.hdf5
  snapshot contains the following number of particles:
    dark      (id = 1): 8820344 particles
    dark2     (id = 2): 3081337 particles
    gas       (id = 0): 5969934 particles
    star      (id = 4): 3059250 particles
    blackhole (id = 5): 0 particles

* reading species: ['star', 'dark']
* reading particles from:
    output/snapshot_600.hdf5

* reading cosmological parameters from:  initial_condition/ic_agora_m12i.conf

* checking sanity of particle properties

* assigning coordinates for 2 host galaxy/halo[s]:
  position = (41821.974, 44122.005, 46288.448) [kpc comoving]
  position = (42326.565, 46242.710, 46897.891) [kpc comoving]
  velocity = (-48.7, 73.2, 96.7) [km / s]
  velocity = (-38.3, 129.5, 143.7) [km / s]

* assigning principal axes of host gal

In [21]:
# everything above carries over, just use 'host', 'host2', 'host3', etc 
# to identify which host you want coordinates relative to

print(part['star'].prop('host.distance'))
print(part['star'].prop('host2.distance'))

[[ 1268.83208172  5564.34890325 -4928.10562341]
 [ 3106.31973213  2376.85209351 -4314.64238128]
 [ 2343.09614995  1783.56843904   860.76900457]
 ...
 [  137.22019795 -1574.3404895   -179.61490314]
 [  137.33256157 -1574.5766965   -179.46876353]
 [  137.33369847 -1574.91948576  -179.89308991]]
[[  764.24101808  3443.64339733 -5537.5485934 ]
 [ 2601.72866849   256.14658759 -4924.08535126]
 [ 1838.5050863   -337.13706688   251.32603459]
 ...
 [ -367.37086569 -3695.04599542  -789.05787312]
 [ -367.25850207 -3695.28220242  -788.91173351]
 [ -367.25736517 -3695.62499168  -789.3360599 ]]


In [22]:
# the code stores coordinates and rotation tensors for each host

print(part.host_positions)
print(part.host_velocities)
print(part.host_rotation_tensors)

[[41821.97367711 44122.00484177 46288.4484585 ]
 [42326.56474076 46242.7103477  46897.89142848]]
[[-48.737286  73.20827   96.66946 ]
 [-38.321564 129.5273   143.74284 ]]
[[[ 0.20397335  0.45612521  0.86622437]
  [ 0.8729429   0.31577278 -0.37183093]
  [-0.44313154  0.83200802 -0.33376204]]

 [[ 0.12491512  0.53307014  0.83679893]
  [ 0.11038452  0.83070206 -0.54566413]
  [-0.98600785  0.16053135  0.04492455]]]


# star + gas particle tracking

Some simulations have pre-compiled HDF5 files for tracking star + gas particles over time. These files are stored in the directory 'track/' (if present). gizmo_track.py contains the code that generates and reads these files.

star\_gas\_pointers\_*.hdf5 files store, for each star and gas particles at z = 0, a pointer to where it was in the catalog at each previous snapshot (replace * with snapshot index). This makes it easy to quickly get the properties of a given star particle at any previous snapshot. These pointers are stored in an HDF5 file, one for each previous snapshot.

### tracking between z = 0 and a previous snapshot

In [100]:
# read catalog of star and gas particles at z = 0

part_at_z0 = gizmo.io.Read.read_snapshots(['star', 'gas'], 'redshift', 0)


# in utilities.simulation.Snapshot():
* reading:  snapshot_times.txt

* input redshift = 0:  using snapshot index = 600, redshift = 0.000


# in gizmo_analysis.gizmo_io.Read():
* reading header from:  output/snapshot_600.hdf5
  snapshot contains the following number of particles:
    dark      (id = 1): 8820344 particles
    dark2     (id = 2): 3081337 particles
    gas       (id = 0): 5969934 particles
    star      (id = 4): 3059250 particles
    blackhole (id = 5): 0 particles

* reading species: ['star', 'gas']
* reading particles from:
    output/snapshot_600.hdf5

* reading cosmological parameters from:  initial_condition/ic_agora_m12i.conf

* checking sanity of particle properties

* assigning coordinates for 1 host galaxy/halo[s]:
  position = (41821.974, 44122.005, 46288.448) [kpc comoving]
  velocity = (-48.7, 73.2, 96.7) [km / s]



In [31]:
# say that you want to find out what they were doing at z = 2
# read in catalog of star particles at z = 2 (snapshot 172)

part_at_z2 = gizmo.io.Read.read_snapshots(['star', 'gas'], 'redshift', 2)


# in utilities.simulation.Snapshot():
* reading:  snapshot_times.txt

* input redshift = 2:  using snapshot index = 172, redshift = 2.000


# in gizmo_analysis.gizmo_io.Read():
* reading header from:  output/snapshot_172.hdf5
  snapshot contains the following number of particles:
    dark      (id = 1): 8820344 particles
    dark2     (id = 2): 3081337 particles
    gas       (id = 0): 8575137 particles
    star      (id = 4): 245223 particles
    blackhole (id = 5): 0 particles

* reading species: ['star', 'gas']
* reading particles from:
    output/snapshot_172.hdf5

* reading cosmological parameters from:  initial_condition/ic_agora_m12i.conf

* checking sanity of particle properties

* assigning coordinates for 1 host galaxy/halo[s]:
  position = (42860.578, 42499.360, 44850.603) [kpc comoving]
  velocity = (-62.4, 121.0, 36.3) [km / s]



In [32]:
# use this read class + function within gizmo_track.py to read star + gas index pointers associated with the catalog z = 1

gizmo.track.ParticlePointerIO.io_pointers(part_at_z2)


# in utilities.basic.io.file_hdf5():
  read file: star_gas_pointers_172.hdf5
    species | |S4, shape = (2,)
    z.gas.index.limits | int64, shape = (2,)
    z.gas.number | int64, shape = ()
    z.particle.number | int64, shape = ()
    z.snapshot.index | int64, shape = ()
    z.star.index.limits | int64, shape = (2,)
    z.star.number | int64, shape = ()
    z0.gas.index.limits | int64, shape = (2,)
    z0.gas.number | int64, shape = ()
    z0.particle.number | int64, shape = ()
    z0.snapshot.index | int32, shape = ()
    z0.star.index.limits | int64, shape = (2,)
    z0.star.number | int64, shape = ()
    z0.to.z.index | int32, shape = (9029184,)


In [140]:
# alternately, can do the same during particle read-in by setting assign_pointers=True

part_at_z2 = gizmo.io.Read.read_snapshots(['star', 'gas'], 'redshift', 2, assign_pointers=True)


# in utilities.simulation.Snapshot():
* reading:  snapshot_times.txt

* input redshift = 2:  using snapshot index = 172, redshift = 2.000


# in gizmo_analysis.gizmo_io.Read():
* reading header from:  output/snapshot_172.hdf5
  snapshot contains the following number of particles:
    dark      (id = 1): 8820344 particles
    dark2     (id = 2): 3081337 particles
    gas       (id = 0): 8575137 particles
    star      (id = 4): 245223 particles
    blackhole (id = 5): 0 particles

* reading species: ['star', 'gas']
* reading particles from:
    output/snapshot_172.hdf5

* reading cosmological parameters from:  initial_condition/ic_agora_m12i.conf

* checking sanity of particle properties

* assigning coordinates for 1 host galaxy/halo[s]:
  position = (42860.578, 42499.360, 44850.603) [kpc comoving]
  velocity = (-62.4, 121.0, 36.3) [km / s]


# in utilities.basic.io.file_hdf5():
  read file: star_gas_pointers_172.hdf5
    species | |S4, shape = (2,)
    z.gas.index.limits | int64, sha

In [141]:
# pointers are stored via dictionary class appended to particle catalog dictionary at the relevant snapshot
# a negative value means that the star formed after this snapshot (so it does not exist at this snapshot)

part_at_z2.Pointer

{'species': array(['star', 'gas'], dtype='<U4'),
 'z.gas.index.limits': array([ 245223, 8820360]),
 'z.gas.number': 8575137,
 'z.particle.number': 8820360,
 'z.snapshot.index': 172,
 'z.star.index.limits': array([     0, 245223]),
 'z.star.number': 245223,
 'z0.gas.index.limits': array([3059250, 9029184]),
 'z0.gas.number': 5969934,
 'z0.particle.number': 9029184,
 'z0.snapshot.index': 600,
 'z0.star.index.limits': array([      0, 3059250]),
 'z0.star.number': 3059250,
 'z0.to.z.index': array([8762407, 6627790, 2897974, ...,  428042, 1883434, 1569509],
       dtype=int32)}

In [142]:
# the particle species that we have compiled tracking pointers for

part_at_z2.Pointer['species']

array(['star', 'gas'], dtype='<U4')

In [143]:
# the snapshot indices at this redshift (z) and at the reference redshift (z = 0)

print(part_at_z2.Pointer['z.snapshot.index'])
print(part_at_z2.Pointer['z0.snapshot.index'])

172
600


In [144]:
# the number of particles at this redshift (z) and at the reference redshift (z = 0)

print(part_at_z2.Pointer['z.star.number'])
print(part_at_z2.Pointer['z.gas.number'])

print(part_at_z2.Pointer['z0.star.number'])
print(part_at_z2.Pointer['z0.gas.number'])

245223
8575137
3059250
5969934


In [146]:
# this stores the actual pointers
# becase gas particles can become star particles, this pipeline concatenates the particle list and 
# stores pointers from this combined star + gas list at z = 0 to z

print(part_at_z2.Pointer['z0.to.z.index'])

# thus, also store the limits of the indices of each species at each snapshot, so can convert back to the index
# within the individual star list or the individual gas list (as stored in the particle catalog)
print(part_at_z2.Pointer['z.star.index.limits'])
print(part_at_z2.Pointer['z.gas.index.limits'])

print(part_at_z2.Pointer['z0.star.index.limits'])
print(part_at_z2.Pointer['z0.gas.index.limits'])

[8762407 6627790 2897974 ...  428042 1883434 1569509]
[     0 245223]
[ 245223 8820360]
[      0 3059250]
[3059250 9029184]


In [147]:
# more simply, use this function to get pointers for a given species from z = 0 to z
# default mode of tracking is going backwards in time (from z = 0 to z)

pointers = part_at_z2.Pointer.get_pointers(species_name_from='star', species_names_to='star')

In [150]:
# say that you have a list of the indices of star particles of interest at z = 0

indices_at_z0 = np.array([5, 8, 13])

# their positions at z = 0

part_at_z0['star']['position'][indices_at_z0]

array([[43395.66430266, 44225.91487342, 46848.42028784],
       [43391.32501013, 44235.3333939 , 46851.26898524],
       [43392.7246372 , 44234.88455716, 46860.08437896]])

In [153]:
# get their indices in the catalog at z = 2
# negative indices means that the star particle did not exist at z = 2

indices_at_z2 = pointers[indices_at_z0]
print(indices_at_z2)

# now you easily can get any property of interest at z = 2, for example, positions
part_at_z2['star']['position'][indices_at_z2]

[93570 93569 93574]


array([[44594.70662236, 42857.76681624, 45680.41942321],
       [44597.17009857, 42856.9103464 , 45683.54318435],
       [44586.14301487, 42869.01990286, 45673.47361522]])

In [154]:
# alternatively, can track particles forward in time by setting forward=True

pointers = part_at_z2.Pointer.get_pointers(species_name_from='star', species_names_to='star', forward=True)

indices_at_z2 = np.array([5, 8, 13])
indices_at_z0 = pointers[indices_at_z2]
print(indices_at_z0)
print(part_at_z0['star']['position'][indices_at_z0])

[1081507 2621944 1378523]
[[41827.95243832 44124.6273934  46289.64224645]
 [41810.05286106 44110.48518841 46285.84784929]
 [41827.05895642 44116.02070015 46284.00376819]]


In [155]:
# also, can track star particles back to progenitor star and gas particles

pointers = part_at_z2.Pointer.get_pointers(species_name_from='star', species_names_to=['star', 'gas'])

# but now, pointers is a *dictionary* that stores both the index and species of each progenitor particle
print(pointers)

# get star indices at z = 0 and see what they were at z = 2
star_indices_at_z0 = np.array([0, 5, 8, 13])
print(pointers['species'][star_indices_at_z0], pointers['index'][star_indices_at_z0])

# get those that were gas particles
masks = np.where(pointers['species'][star_indices_at_z0] == 'gas')[0]

gas_indices_at_z2 = pointers['index'][star_indices_at_z0[masks]]

print(gas_indices_at_z2)
print(part_at_z2['gas']['position'][gas_indices_at_z2])

{'index': array([8517184, 6382567, 2652751, ..., 5870729,  297634,  179265],
      dtype=int32), 'species': array(['gas', 'gas', 'gas', ..., 'gas', 'gas', 'star'], dtype='<U4')}
['gas' 'star' 'star' 'star'] [8517184   93570   93569   93574]
[8517184]
[[42845.52824108 42506.12287672 44870.50121988]]


In [156]:
# similar for working forward in time, to track gas particles at z that can be star or gas particles at z = 0

pointers = part_at_z2.Pointer.get_pointers(species_name_from='gas', species_names_to=['star', 'gas'], forward=True)

# get star indices at z = 0 and see what they were at z = 2
gas_indices_at_z2 = np.array([0, 5, 8, 13])
print(pointers['species'][gas_indices_at_z2])
print(pointers['index'][gas_indices_at_z2])

# get those that are star particles at z = 0
masks = np.where(pointers['species'][gas_indices_at_z2] == 'star')[0]

star_indices_at_z0 = pointers['index'][gas_indices_at_z2[masks]]

print(star_indices_at_z0)
print(part_at_z0['star']['position'][star_indices_at_z0])

['star' 'star' 'gas' 'gas']
[ 215205 1917430 1826927 4148144]
[ 215205 1917430]
[[41823.76116895 44122.68646199 46287.49155757]
 [41813.98704585 44118.76742237 46303.17274406]]


### tracking between two snapshots both at z > 0

In [157]:
# particle tracking also can handle tracking particles between any two snapshots

# read catalogs of star and gas particles at z = 1 and 2, including their pointers relative to z = 0
# can set ssign_pointers=True, automatically appends pointer class to particle catalog
part_at_z1 = gizmo.io.Read.read_snapshots(['star', 'gas'], 'redshift', 1, assign_pointers=True)
part_at_z2 = gizmo.io.Read.read_snapshots(['star', 'gas'], 'redshift', 2, assign_pointers=True)


# in utilities.simulation.Snapshot():
* reading:  snapshot_times.txt

* input redshift = 1:  using snapshot index = 277, redshift = 1.000


# in gizmo_analysis.gizmo_io.Read():
* reading header from:  output/snapshot_277.hdf5
  snapshot contains the following number of particles:
    dark      (id = 1): 8820344 particles
    dark2     (id = 2): 3081337 particles
    gas       (id = 0): 7498674 particles
    star      (id = 4): 1333580 particles
    blackhole (id = 5): 0 particles

* reading species: ['star', 'gas']
* reading particles from:
    output/snapshot_277.hdf5

* reading cosmological parameters from:  initial_condition/ic_agora_m12i.conf

* checking sanity of particle properties

* assigning coordinates for 1 host galaxy/halo[s]:
  position = (42434.347, 43258.424, 45265.678) [kpc comoving]
  velocity = (-62.5, 90.3, 88.6) [km / s]


# in utilities.basic.io.file_hdf5():
  read file: star_gas_pointers_277.hdf5
    species | |S4, shape = (2,)
    z.gas.index.limits | int64, sha

In [158]:
# now just need to append intermediate redshift pointers (to z = 1) to pointers at z = 2

part_at_z2.Pointer.add_intermediate_pointers(part_at_z1.Pointer)

In [159]:
# now access pointers from z = 1 to z = 2, by setting intermediate_z=True

pointers = part_at_z2.Pointer.get_pointers(
    species_name_from='star', species_names_to=['star', 'gas'], intermediate_z=True)

# get star indices at z = 0 and see what they were at z = 2
star_indices_at_z1 = np.array([0, 5, 8, 13])
print(pointers['species'][star_indices_at_z1])
print(pointers['index'][star_indices_at_z1])

# get those that are star particles at z = 2
masks = np.where(pointers['species'][star_indices_at_z1] == 'star')[0]

star_indices_at_z2 = pointers['index'][star_indices_at_z1[masks]]

print(star_indices_at_z2)
print(part_at_z2['star']['position'][star_indices_at_z2])

['star' 'gas' 'gas' 'gas']
[ 107166 1169600 6377478  239484]
[107166]
[[43535.53900573 42053.83122207 46265.70989359]]


In [160]:
# if you just want to track single species of particles (star -> star or gas -> gas) between two snapshots,
# read_pointers_between_snapshots() makes it easy to get the pointer indices between any two snapshots

# tracking forwards in time
pointers_z2_to_z1 = gizmo.track.ParticlePointerIO.read_pointers_between_snapshots(
    snapshot_index_from=172, snapshot_index_to=277, species_name='star')

# for example, see how far star particles have moved
print(part_at_z2['star']['position'] - part_at_z1['star']['position'][pointers_z2_to_z1])


# tracking backwards in time
pointers_z1_to_z2 = gizmo.track.ParticlePointerIO.read_pointers_between_snapshots(
    snapshot_index_from=277, snapshot_index_to=172, species_name='star')

# in this case, need to select stars that existed as stars at z = 2
masks = (pointers_z1_to_z2 >= 0)

# see how far star particles have moved
print(part_at_z1['star']['position'][masks] - part_at_z1['star']['position'][pointers_z1_to_z2[masks]])


# in utilities.basic.io.file_hdf5():
  read file: star_gas_pointers_277.hdf5
    species | |S4, shape = (2,)
    z.gas.index.limits | int64, shape = (2,)
    z.gas.number | int64, shape = ()
    z.particle.number | int64, shape = ()
    z.snapshot.index | int64, shape = ()
    z.star.index.limits | int64, shape = (2,)
    z.star.number | int64, shape = ()
    z0.gas.index.limits | int64, shape = (2,)
    z0.gas.number | int64, shape = ()
    z0.particle.number | int64, shape = ()
    z0.snapshot.index | int64, shape = ()
    z0.star.index.limits | int64, shape = (2,)
    z0.star.number | int64, shape = ()
    z0.to.z.index | int32, shape = (9029184,)

# in utilities.basic.io.file_hdf5():
  read file: star_gas_pointers_172.hdf5
    species | |S4, shape = (2,)
    z.gas.index.limits | int64, shape = (2,)
    z.gas.number | int64, shape = ()
    z.particle.number | int64, shape = ()
    z.snapshot.index | int64, shape = ()
    z.star.index.limits | int64, shape = (2,)
    z.star.number |

In [161]:
# do the same, but for gas

# tracking forwards in time
pointers_z2_to_z1 = gizmo.track.ParticlePointerIO.read_pointers_between_snapshots(
    snapshot_index_from=172, snapshot_index_to=277, species_name='gas')

# ensure still gas particle at z = 1
masks = (pointers_z2_to_z1 >= 0)

print(part_at_z2['gas']['position'][masks] - part_at_z1['gas']['position'][pointers_z2_to_z1[masks]])

# tracking backwards in time
pointers_z1_to_z2 = gizmo.track.ParticlePointerIO.read_pointers_between_snapshots(
    snapshot_index_from=277, snapshot_index_to=172, species_name='gas')

# for gas, still have to ensure positive pointers, even if tracking backwards in time,
# because a few gas particles that leave the zoom-in region get culled (for numerical stability) by z = 0
# (remember that the pointers always route through z = 0)
masks = (pointers_z1_to_z2 >= 0)

print(part_at_z1['gas']['position'][masks] - part_at_z2['gas']['position'][pointers_z1_to_z2[masks]])


# in utilities.basic.io.file_hdf5():
  read file: star_gas_pointers_277.hdf5
    species | |S4, shape = (2,)
    z.gas.index.limits | int64, shape = (2,)
    z.gas.number | int64, shape = ()
    z.particle.number | int64, shape = ()
    z.snapshot.index | int64, shape = ()
    z.star.index.limits | int64, shape = (2,)
    z.star.number | int64, shape = ()
    z0.gas.index.limits | int64, shape = (2,)
    z0.gas.number | int64, shape = ()
    z0.particle.number | int64, shape = ()
    z0.snapshot.index | int64, shape = ()
    z0.star.index.limits | int64, shape = (2,)
    z0.star.number | int64, shape = ()
    z0.to.z.index | int32, shape = (9029184,)

# in utilities.basic.io.file_hdf5():
  read file: star_gas_pointers_172.hdf5
    species | |S4, shape = (2,)
    z.gas.index.limits | int64, shape = (2,)
    z.gas.number | int64, shape = ()
    z.particle.number | int64, shape = ()
    z.snapshot.index | int64, shape = ()
    z.star.index.limits | int64, shape = (2,)
    z.star.number |

# star particle formation coordinates

As part of star particle tracking, we store the position and velocity of each star particle immediately after it formed.

Within track/, star\_form\_coordinates\_600.hdf5 stores, for each star particle at z = 0, its 3-D distance and 3-D velocity wrt to the main host galaxy at the first snapshot after it formed. These coordinates are aligned with the principal (major, intermediate, minor) axes of the stellar disk (as defined via its moment of inertia tensor) at that snapshot.

In [133]:
# use the function within gizmo_track.py to read this file and assign values directly to the catalog at z = 0

gizmo.track.ParticleCoordinate.io_formation_coordinates(part_at_z0)


# in utilities.basic.io.file_hdf5():
  read file: star_form_coordinates_600.hdf5
    center.position | float32, shape = (601, 3)
    center.velocity | float32, shape = (601, 3)
    form.host.distance | float32, shape = (3059250, 3)
    form.host.velocity | float32, shape = (3059250, 3)
    id | uint32, shape = (3059250,)
    principal.axes.vectors | float32, shape = (601, 3, 3)


In [ ]:
# more conveniently, you can read the formation coordinates of star particles during snapshot read-in

part_at_z0 = gizmo.io.Read.read_snapshots(
    ['star'], 'redshift', 0, assign_host_principal_axes=True, assign_formation_coordinates=True)

In [134]:
# 3-D distance at formation
# this is aligned with the principal axes of the host galaxy at that time [kpc physical]
# the principal axes are defined *independently* at each snapshot
# distance along dimension 0 is aligned with the major axis
# distance along dimension 1 is algined with the intermediate axis
# distance along dimension 2 is aligned with the minor (Z) axis

part_at_z0['star']['form.host.distance']

array([[    3.8351834,     6.170289 ,    -1.4488623],
       [  951.6061   , -1143.819    ,   541.5925   ],
       [ 1258.5391   ,   183.60645  ,   -92.80096  ],
       ...,
       [  542.5843   ,  -580.9797   ,   927.32684  ],
       [ -376.8372   ,   349.8039   ,  -245.89764  ],
       [ -275.3792   ,   -35.97139  ,  -272.96063  ]], dtype=float32)

In [135]:
# as before, add 'total' to get the total scalar (absolute) distance wrt the host galaxy at formation [kpc physical]
# this is a derived quantity, so need to call via .prop()

part_at_z0['star'].prop('form.host.distance.total')

array([   7.408124, 1583.4136  , 1275.2427  , ..., 1221.4214  ,
        569.9427  ,  389.4036  ], dtype=float32)

In [136]:
# add 'cylindrical' to get 3-D distance at formation wrt the host galaxy in cylindrical coordinates [kpc physical]

part_at_z0['star'].prop('form.host.distance.cylindrical')

array([[ 7.2650599e+00, -1.4488623e+00,  1.0146770e+00],
       [ 1.4879099e+03,  5.4159253e+02,  5.4063134e+00],
       [ 1.2718616e+03, -9.2800957e+01,  1.4486657e-01],
       ...,
       [ 7.9494348e+02,  9.2732684e+02,  5.4636278e+00],
       [ 5.1416827e+02, -2.4589764e+02,  2.3933804e+00],
       [ 2.7771866e+02, -2.7296063e+02,  3.2714822e+00]], dtype=float32)

In [137]:
# these values look more reasonable if you restrict to star particles that formed within the host galaxy

# select particles formed at d = 0 - 8 kpc physical
part_indices = ut.array.get_indices(part_at_z0['star'].prop('form.host.distance.total'), [0, 8])

part_at_z0['star'].prop('form.host.distance.cylindrical', part_indices)

array([[ 7.26506   , -1.4488623 ,  1.014677  ],
       [ 2.819624  , -0.01174179,  4.65897   ],
       [ 2.4207215 , -0.02199288,  3.6387615 ],
       ...,
       [ 2.7438505 , -1.4894025 ,  5.987568  ],
       [ 3.6302092 , -0.01234316,  3.3655412 ],
       [ 1.5276729 , -0.12618025,  1.8085258 ]], dtype=float32)

In [138]:
# same thing for velocity at formation

print(part_at_z0['star']['form.host.velocity'])
print(part_at_z0['star'].prop('form.host.velocity.total'))
print(part_at_z0['star'].prop('form.host.velocity.cylindrical'))

[[ 5.10321930e+02  8.53348755e+02  2.34322433e+02]
 [ 4.29511480e-02 -1.29415512e+02  3.22944736e+00]
 [ 1.82360718e+02 -1.09645996e+02  3.08418255e+01]
 ...
 [ 3.11529217e+01 -1.06510910e+02 -1.64038372e+00]
 [-9.91549301e+01 -8.34163761e+00  2.34269543e+01]
 [-1.11417809e+02  4.18189201e+01 -2.22872696e+01]]
[1021.5379   129.45581  215.00905 ...  110.98545  102.22575  121.07631]
[[ 994.1538     234.32243     17.056305 ]
 [  99.514626     3.2294474  -82.735825 ]
 [ 164.622       30.841825  -134.82314  ]
 ...
 [  99.10612     -1.6403837  -49.930504 ]
 [  66.996216    23.426954    73.57168  ]
 [ 105.06267    -22.28727    -55.897987 ]]


In [139]:
# recall that formation postion + velocity as stored relative to each host's principal axes
# and that principal axes are computed independently at each snapshot
# the tracking code also stores each host's rotation tensor (for its principal axes) at each snapshot
# so you can use this to compute formation coordinates in the box's x,y,z coordinates if you want

part_at_z0['star'].host_rotation_tensors_at_snapshots

array([[[[        nan,         nan,         nan],
         [        nan,         nan,         nan],
         [        nan,         nan,         nan]],

        [[        nan,         nan,         nan],
         [        nan,         nan,         nan],
         [        nan,         nan,         nan]],

        [[        nan,         nan,         nan],
         [        nan,         nan,         nan],
         [        nan,         nan,         nan]],

        ...,

        [[-0.23860915,  0.24924965,  0.9385842 ],
         [ 0.8640545 ,  0.49563974,  0.08804033],
         [-0.4432556 ,  0.83199507, -0.33362946]],

        [[-0.01853178,  0.36362258,  0.93136203],
         [ 0.8962332 ,  0.418959  , -0.14573726],
         [-0.44319585,  0.8320168 , -0.3336547 ]],

        [[ 0.20290324,  0.4557217 ,  0.86668795],
         [ 0.8732139 ,  0.31629786, -0.37074673],
         [-0.4430889 ,  0.8320297 , -0.33376467]]]], dtype=float32)

# profile of properties

A common task that you might have is to compute a radial profile of a given quantity, such as mass density, average age, median metallicity, etc.

The high-level functions below make this easier to do.

In [ ]:
# first, initiate an instance of SpeciesProfileClass
# as you initialize,choose your distance/radius binning scheme: 
#   'log' v 'linear', distance limits, bin width, number of spatial dimensions of profile
# refer to ut.binning.DistanceBinClass() for more

# linear binning from 0 to 20 kpc with 1 kpc bin width, assuming a 3-D profile
SpeciesProfile = ut.particle.SpeciesProfileClass(scaling='linear', limits=[0, 20], width=1, dimension_number=3)

In [ ]:
# using this binning scheme,
# compute sum/histogram/density of mass of star particles in each bin
# this returns a bunch of summed properties via a dictionary

pro = SpeciesProfile.get_sum_profiles(part, 'star', 'mass')

In [ ]:
# in principle, you can supply a list of multiple species, and it will compute profiles for each
# thus, it returns a dictionary for each species

pro.keys()

In [ ]:
# the quantities that it stores in each bin

pro['star'].keys()

In [ ]:
# alternately, you may want to compute profiles along a disks R or Z axes
# if so, first define the dimensionality of the profile when you initiate the class

# log binning from 0.1 to 10 kpc with 0.1 dex bin width, assuming a 2-D profile (along R)
SpeciesProfile = ut.particle.SpeciesProfileClass(scaling='log', limits=[0.1, 10], width=0.1, dimension_number=2)

In [ ]:
# set rotation = True to force it to compute profiles along the principal axes (assuming that you read them in)
# use other_axis_distance_limits to limit the extent along the other axis, 
#   in this case, limit the Z axis to within +/- 1 kpc (in the profile, all distances are absolute)

pro = SpeciesProfile.get_sum_profiles(part, 'star', 'mass', rotation=True, other_axis_distance_limits=[0, 1])

In [ ]:
# similarly, do this to compute profiles along Z

# log binning from 0.1 to 10 kpc with 0.1 dex bin width, assuming a 1-D profile (along Z)
SpeciesProfile = ut.particle.SpeciesProfileClass(scaling='log', limits=[0.1, 10], width=0.1, dimension_number=1)

# limit the R axex to [5, 8] kpc 
pro = SpeciesProfile.get_sum_profiles(part, 'star', 'mass', rotation=True, other_axis_distance_limits=[5, 8])

In [ ]:
# using the same binning scheme
# this function computes various statistics of a property of star particles in each bin
# by default, it weights the property by the mass of each particle
# this returns a bunch of statistics via a dictionary

pro = SpeciesProfile.get_statistics_profiles(
    part, 'star', 'age', weight_by_mass=True, rotation=True, other_axis_distance_limits=[5, 8])

In [ ]:
# the quantities that it stores in each bin

pro['star'].keys()