This is a tutorial on reading FIRE-2 Gizmo simulation snapshots and analyzing the data.

First, move within a simulation directory, or set simulation_directory below to point to one. This directory should contain:
(1) a sub-directory 'output/' that contains snapshot files
(2) a text file 'snapshot_times.txt' that lists the scale-factors, redshifts, times, and indices of all snapshots stored from the simulation
(3) optionally (but ideally) an 'initial_condition/' directory that contains a MUSIC configuration file named '*.conf' that stores all 6 cosmological parameters. if the simulation directory does not assume, this, gizmo_analysis will assume the same cosmological parameters as in the AGORA simulation

Ensure that the gizmo_analysis and utilities package directories are in your python path, then...

In [7]:
import gizmo_analysis as gizmo
import utilities as ut

import numpy as np

In [8]:
# you can access the files as named or use the aliases in __init__.py to keep it shorter 
# for example, these are the same:

gizmo.gizmo_io
gizmo.io

<module 'gizmo_analysis.gizmo_io' from '/Users/awetzel/work/research/analysis/gizmo_analysis/gizmo_io.py'>

# read particle data

In [54]:
# we recommend that you copy this jupyter notebook tutorial into a simulation directory 
# (for example, m12i_res7100/) and run from there.
# however, you can set simulation_directory below to point to any simulation directory and then run this notebook from anywhere

# use this is you are running from within a simulation directory
simulation_directory = '.'

# use this to point to a specific simulation directory, if you run this notebook from somwhere else
#simulation_directory = '/Users/awetzel/work/research/simulation/gizmo/simulations/m12/m12i/m12i_res57000'

In [55]:
# read star and dark-matter particles at z = 0

part = gizmo.io.Read.read_snapshots(['star', 'dark'], 'redshift', 0, simulation_directory)


# in utilities.simulation.Snapshot():
* reading:  Users/awetzel/work/research/simulation/gizmo/simulations/m12/m12i/m12i_res57000/snapshot_times.txt

* input redshift = 0:  using snapshot index = 600, redshift = 0.000


# in gizmo_analysis.gizmo_io.Read():
* reading header from:  Users/awetzel/work/research/simulation/gizmo/simulations/m12/m12i/m12i_res57000/output/snapshot_600.hdf5
  snapshot contains the following number of particles:
    dark      (id = 1): 8820344 particles
    dark2     (id = 2): 3081337 particles
    gas       (id = 0): 5969934 particles
    star      (id = 4): 3059250 particles
    blackhole (id = 5): 0 particles

* reading species: ['star', 'dark']
* reading particles from:
    Users/awetzel/work/research/simulation/gizmo/simulations/m12/m12i/m12i_res57000/output/snapshot_600.hdf5

* reading cosmological parameters from:  Users/awetzel/work/research/simulation/gizmo/simulations/m12/m12i/m12i_res57000/initial_condition/ic_agora_m12i.conf

* checking sanity of p

In [9]:
# alternately, read all particle species at z = 0

part = gizmo.io.Read.read_snapshots('all', 'redshift', 0, simulation_directory)


# in utilities.simulation.Snapshot():
* reading:  Users/awetzel/work/research/simulation/gizmo/simulations/m12/m12i/m12i_res7100/snapshot_times.txt

* input redshift = 0:  using snapshot index = 600, redshift = 0.000


# in gizmo_analysis.gizmo_io.Read():
* reading header from:  Users/awetzel/work/research/simulation/gizmo/simulations/m12/m12i/m12i_res7100/output/snapdir_600/snapshot_600.0.hdf5
  snapshot contains the following number of particles:
    dark      (id = 1): 70514272 particles
    dark2     (id = 2): 5513331 particles
    gas       (id = 0): 57060074 particles
    star      (id = 4): 13976485 particles
    blackhole (id = 5): 0 particles

* reading species: ['dark', 'dark2', 'gas', 'star']
* reading particles from:
    snapshot_600.0.hdf5
    snapshot_600.1.hdf5
    snapshot_600.2.hdf5
    snapshot_600.3.hdf5

* reading cosmological parameters from:  Users/awetzel/work/research/simulation/gizmo/simulations/m12/m12i/m12i_res7100/initial_condition/ic_agora_m12i.conf

* che

In [11]:
# we store each particle species as its own dictionary
# 'star' = stars, 'gas' = gas, 'dark' = dark matter,
# 'dark2', 'dark3', 'dark4', etc = low-resolution dark matter (but you rarely will be interested in this)

part.keys()

dict_keys(['dark', 'dark2', 'gas', 'star'])

In [12]:
# the properties of star particles are stored via dictionary

part['star'].keys()

dict_keys(['position', 'mass', 'massfraction', 'id.child', 'id.generation', 'id', 'potential', 'form.scalefactor', 'velocity'])

In [13]:
# list the properties of dark-matter particles

part['dark'].keys()

dict_keys(['position', 'mass', 'id.child', 'id.generation', 'id', 'potential', 'velocity'])

In [14]:
# list the properties of gas particles

part['gas'].keys()

dict_keys(['position', 'density', 'electron.fraction', 'temperature', 'mass', 'massfraction', 'hydrogen.neutral.fraction', 'id.child', 'id.generation', 'id', 'potential', 'smooth.length', 'sfr', 'velocity'])

# particle properties

In [16]:
# 3-D position of each star particle, stored in a particle_number x dimension_number array [kpc comoving]

part['star']['position']

array([[66767.26081251, 33338.43269396, 33932.56150561],
       [45775.6955822 , 44156.6346538 , 48521.62410745],
       [46577.95875962, 45155.54312985, 48568.13059231],
       ...,
       [40880.57503257, 41838.63478439, 46003.25210661],
       [40751.14753809, 41723.01529911, 45831.83965826],
       [40763.37457623, 41689.45972354, 45872.69257229]])

In [17]:
# 3-D velocity of each star particle (particle_number x dimension_number array) [km / s]

part['star']['velocity']

array([[ 903.24445 , -337.15488 , -448.82474 ],
       [2158.4524  ,   87.50453 , 1342.2155  ],
       [ 329.9966  ,  -58.21963 ,  254.37834 ],
       ...,
       [ -49.03016 ,   44.50777 ,   71.2202  ],
       [ -56.024612,   28.844072,   66.678444],
       [ -55.499584,   27.759323,   67.18623 ]], dtype=float32)

In [18]:
# mass of each star particle [Msun]

part['star']['mass']

array([ 6320.636 , 12393.744 ,  4689.9375, ...,  5306.1577,  5434.9014,
        5381.738 ], dtype=float32)

In [19]:
# formation scale-factor of each star particle

part['star']['form.scalefactor']

array([0.37762484, 0.89081126, 0.25509095, ..., 0.2102304 , 0.24331866,
       0.24331439], dtype=float32)

In [20]:
# IMPORTANT FEATURE
# use .prop() to compute derived quantities, such as the time [in Gyr] when each star particle formed
# see gizmo.io.ParticleDictionaryClass for all options for derived quantities

part['star'].prop('form.time')

array([ 4.03834671, 12.22887105,  2.27725537, ...,  1.70920112,
        2.12346332,  2.12340804])

In [21]:
# similarly, get the age of each star particle (the lookback time to when it formed) [Gyr]

part['star'].prop('age')

array([ 9.76040017,  1.56987583, 11.52149151, ..., 12.08954577,
       11.67528356, 11.67533884])

In [24]:
# get the mass of each star particle when it formed [Msun], using the stellar evolution tracks in Gizmo
# this initially sets up an internally stored spline to compute this

part['star'].prop('form.mass')

array([ 9278.52894705, 23814.78994177,  6883.22964775, ...,
        7817.70278585,  7996.13956357,  7915.62061537])

# elemental abundances / metallicities

In [25]:
# elemental abundances are stored in the particle catalog as linear *mass fraction*
# one value for each element, in a particle_number x element_number array
# the first value is the mass fraction of all metals (everything not H, He)
# then He, C, N, O, etc

part['star']['massfraction']

array([[6.0437708e-03, 2.5534785e-01, 7.1185018e-04, ..., 1.0893279e-04,
        1.1798347e-05, 2.1929388e-04],
       [5.4124359e-02, 3.1047031e-01, 1.0200043e-02, ..., 7.9930318e-04,
        8.8536028e-05, 2.1123942e-03],
       [8.2049592e-05, 2.5007892e-01, 1.0591144e-05, ..., 1.5061760e-06,
        1.6711007e-07, 3.2767741e-06],
       ...,
       [2.3722230e-03, 2.5235808e-01, 3.1619624e-04, ..., 4.0682979e-05,
        4.3580399e-06, 7.0938091e-05],
       [2.5177756e-03, 2.5172576e-01, 2.0903027e-04, ..., 4.6831501e-05,
        5.0457384e-06, 8.8196532e-05],
       [2.2657898e-03, 2.5153482e-01, 1.8845814e-04, ..., 4.3525546e-05,
        4.7441872e-06, 9.4178256e-05]], dtype=float32)

In [26]:
# get individual elements by their array index

# total metal mass fraction (everything not H, He) is index 0
print(part['star']['massfraction'][:, 0])

# iron is index 10
print(part['star']['massfraction'][:, 10])

[6.0437708e-03 5.4124359e-02 8.2049592e-05 ... 2.3722230e-03 2.5177756e-03
 2.2657898e-03]
[2.1929388e-04 2.1123942e-03 3.2767741e-06 ... 7.0938091e-05 8.8196532e-05
 9.4178256e-05]


In [27]:
# alternately use .prop() to compute derived quantities, including calling element by its name or symbol
# see gizmo.io.ParticleDictionaryClass for all options for derived quantities

print(part['star'].prop('massfraction.metals'))
print(part['star'].prop('massfraction.carbon'))
print(part['star'].prop('massfraction.iron'))
print(part['star'].prop('massfraction.fe'))  # you can use name or symbol

[6.0437708e-03 5.4124359e-02 8.2049592e-05 ... 2.3722230e-03 2.5177756e-03
 2.2657898e-03]
[7.1185018e-04 1.0200043e-02 1.0591144e-05 ... 3.1619624e-04 2.0903027e-04
 1.8845814e-04]
[2.1929388e-04 2.1123942e-03 3.2767741e-06 ... 7.0938091e-05 8.8196532e-05
 9.4178256e-05]
[2.1929388e-04 2.1123942e-03 3.2767741e-06 ... 7.0938091e-05 8.8196532e-05
 9.4178256e-05]


In [29]:
# also use .prop() to compute metallicity [Z / H]
# for example, iron abundance [Fe / H] :=
#   log10((mass_iron / mass_hydrogen)_particle / (mass_iron / mass_hydrogen)_sun)
# gizmo_analysis assumes solar abundances from Asplund et al 2009

print(part['star'].prop('metallicity.total'))
print(part['star'].prop('metallicity.fe'))

[-0.3457968   0.60628796 -2.2130284  ... -0.7519493  -0.72608775
 -0.77188516]
[-0.77062804  0.21312043 -2.596208   ... -1.2607751  -1.166203
 -1.1377039 ]


In [30]:
# also use .prop() to compute simple arithmetic combinations, such as [Mg / Fe]

part['star'].prop('metallicity.mg - metallicity.fe')

array([0.36855963, 0.21050921, 0.31733322, ..., 0.4481188 , 0.4061309 ,
       0.32690054], dtype=float32)

In [31]:
# refer to utilities.basic.constant for assumed solar values (Asplund et al 2009) and other constants

ut.constant.sun_composition

{'hydrogen': {'massfraction': 0.7381},
 'helium': {'abundance': 0.08511380382023759, 'massfraction': 0.2485},
 'metals': {'massfraction': 0.0134},
 'total': {'massfraction': 0.0134},
 'carbon': {'abundance': 0.0002691534803926914,
  'massfraction': 0.002367134813394483},
 'nitrogen': {'abundance': 6.760829753919819e-05,
  'massfraction': 0.0006934106379733354},
 'oxygen': {'abundance': 0.0004897788193684457,
  'massfraction': 0.005737971271592906},
 'neon': {'abundance': 8.51138038202376e-05,
  'massfraction': 0.0012576777529689648},
 'magnesium': {'abundance': 3.9810717055349695e-05,
  'massfraction': 0.0007085170384267315},
 'silicon': {'abundance': 3.235936569296281e-05,
  'massfraction': 0.0006654827968172229},
 'sulphur': {'abundance': 1.3182567385564074e-05,
  'massfraction': 0.00030951800499730997},
 'calcium': {'abundance': 2.1877616239495517e-06,
  'massfraction': 6.420379718268677e-05},
 'iron': {'abundance': 3.1622776601683795e-05,
  'massfraction': 0.0012931667271008657},
 

# meta-data about simulation

The dictionary that stores the particle catalog is actually a dictionary class. We store meta-data about the simulation and ancillary data/functions via appended dictionaries, classes, and arrays.

In [32]:
# dictionary of useful information about the simulation

part.info

{'box.length': 85470.08547008547,
 'compression.level': 0,
 'compression.version': 'v0.2',
 'has.cooling': 1,
 'has.double.precision': 0,
 'has.feedback': 1,
 'has.ic.info': 3,
 'has.metals': 11,
 'has.star.formation': 1,
 'has.star.age': 1,
 'hubble': 0.702,
 'particle.masses': array([0., 0., 0., 0., 0., 0.]),
 'file.number.per.snapshot': 4,
 'particle.numbers.in.file': array([13818978, 17322170,  1679251,        0,  3829217,        0],
       dtype=int32),
 'particle.numbers.total': array([57060074, 70514272,  5513331,        0, 13976485,        0],
       dtype=uint32),
 'particle.numbers.total.high.word': array([0, 0, 0, 0, 0, 0], dtype=uint32),
 'omega_matter': 0.272,
 'omega_lambda': 0.728,
 'compression.readme': 'This snapshot is part of the Feedback in Realistic Environments (FIRE) project -- Use, modification, or distribution only permitted with approval of the PI and the FIRE team -- No warranty, use at your own risk -- compactify_hdf5 (c) RF 2018',
 'redshift': 0.0,
 'cosmol

In [34]:
# dictionary of information about the single snapshot that you read
# its index (number), scale-factor, redshift, time, lookback-time

part.snapshot

{'index': 600,
 'redshift': 0.0,
 'scalefactor': 1.0,
 'time': 13.798746883488086,
 'time.lookback': 0.0,
 'time.hubble': 13.92866412650697}

In [36]:
# dictionary class with information about *all* snapshots (typically ~600) that we saved for this simulation

print(part.Snapshot.keys())
print(part.Snapshot['redshift'][:10])

dict_keys(['index', 'scalefactor', 'redshift', 'time', 'time.width'])
[99.         19.         15.         14.60591125 14.23076916 13.87323952
 13.53211021 13.20627785 12.89473724 12.5965662 ]


In [37]:
# dictionary class of cosmological parameters, with internal functions for cosmological conversions
# see utilities.cosmology for more on this

part.Cosmology

{'omega_lambda': 0.728,
 'omega_matter': 0.272,
 'omega_baryon': 0.0455,
 'omega_curvature': 0.0,
 'omega_dm': 0.22650000000000003,
 'baryon.fraction': 0.16727941176470587,
 'hubble': 0.7020000000000001,
 'sigma_8': 0.807,
 'n_s': 0.961,
 'w': -1.0}

See gizmo_plot.py (called via gizmo.plot) for examples of high-level analysis, including plotting these data.

See utilities/particle.py (called via ut.particle) for mid-level analysis functions that may be useful.

See other modules within utilities for low-level functions that may be useful.

# coordinates of host galaxy/halo and principal axes of stellar disk

If you enable read_snapshots(assign_host_coordinates=True) (True by default), then during read-in gizmo_analysis assigns the position and velocity of the host galaxy/halo (using stars for a baryonic simulations and dark matter for a DM-only simulation). The code stores these coordinates in arrays appended to the particle catalog.

Most simulations have a single host galaxy/halo, but some (like ELVIS) contain 2 (or more). You can control the number of hosts via: read_snapshots(host_number=2) (by deafult, host_number=1).

Once the code assigns the coordinates of each host, it also can compute the principal axes (rotation tensor) of each host's stellar disk. Enable this via: read_snapshots(assign_host_principal_axes=True) (by default, assign_host_principal_axes=False).

In [38]:
# position [kpc comoving] and velocity [km / s] of the center of each host galaxy
# can store multiple hosts, though usually just one

print(part.host_positions)
print(part.host_velocities)

[[41792.14655358 44131.23458952 46267.67922214]]
[[-52.451195  71.85305   95.19773 ]]


In [39]:
# compute and assign principal axes (defined via moment of inertia tensor) of stars during read in as below

part = gizmo.io.Read.read_snapshots(['star', 'dark'], 'redshift', 0, simulation_directory, assign_host_principal_axes=True)


# in utilities.simulation.Snapshot():
* reading:  Users/awetzel/work/research/simulation/gizmo/simulations/m12/m12i/m12i_res7100/snapshot_times.txt

* input redshift = 0:  using snapshot index = 600, redshift = 0.000


# in gizmo_analysis.gizmo_io.Read():
* reading header from:  Users/awetzel/work/research/simulation/gizmo/simulations/m12/m12i/m12i_res7100/output/snapdir_600/snapshot_600.0.hdf5
  snapshot contains the following number of particles:
    dark      (id = 1): 70514272 particles
    dark2     (id = 2): 5513331 particles
    gas       (id = 0): 57060074 particles
    star      (id = 4): 13976485 particles
    blackhole (id = 5): 0 particles

* reading species: ['star', 'dark']
* reading particles from:
    snapshot_600.0.hdf5
    snapshot_600.1.hdf5
    snapshot_600.2.hdf5
    snapshot_600.3.hdf5

* reading cosmological parameters from:  Users/awetzel/work/research/simulation/gizmo/simulations/m12/m12i/m12i_res7100/initial_condition/ic_agora_m12i.conf

* checking sanity of 

In [40]:
# we then store the rotation tensor[s], to rotate into the principal axes for each host, for each host via

print(part.host_rotations)

[[[ 0.38804234 -0.92127503 -0.02598965]
  [-0.78055724 -0.34350448  0.52224043]
  [-0.49005463 -0.18236499 -0.85240218]]]


In [41]:
# now you can compute different types of distances of star particles from the center of each host galaxy
# compute 3-D distance from the host center along simulation's default x,y,z cartesian axes [kpc physical]

part['star'].prop('host.distance')

array([[ 24975.11425893, -10792.80189557, -12335.11771654],
       [  3983.54902862,     25.40006428,   2253.9448853 ],
       [  4785.81220605,   1024.30854032,   2300.45137017],
       ...,
       [  -911.57152101,  -2292.59980513,   -264.42711553],
       [ -1040.99901548,  -2408.21929041,   -435.83956389],
       [ -1028.77197735,  -2441.77486598,   -394.98664985]])

In [42]:
# add '.total' to compute total (scalar) distance [kpc physical]

part['star'].prop('host.distance.total')

array([29872.99841135,  4577.07063226,  5407.89080547, ...,
        2481.30977587,  2659.54041639,  2678.92716047])

In [43]:
# add '.principal' to compute 3-D distance aligned with the principal (major, intermediate, minor) axes of each host's stellar disk [kpc physical]

part['star'].prop('host.distance.principal')

array([[ 19955.12594025, -22229.02766731,    243.54005743],
       [  1463.80598701,  -1941.01193546,  -3878.05624913],
       [   853.63993849,  -2886.06623758,  -4493.01719244],
       ...,
       [  1765.25898462,   1360.95752389,   1090.20802567],
       [  1826.00793168,   1412.18039258,   1320.83185858],
       [  1860.6047012 ,   1435.49802325,   1286.13619116]])

In [44]:
# add '.cylindrical' or '.cyl' to compute 3-D distance aligned with the principal axes in cylindrical coordinates
# first value is along the major axes (R, positive definite)
# second value is vertical height wrt the disk (Z, signed)
# third value is angle (phi, 0 to 2 * pi)

part['star'].prop('host.distance.principal.cylindrical')

array([[ 2.98720057e+04,  2.43540057e+02,  5.44393509e+00],
       [ 2.43110166e+03, -3.87805625e+03,  5.35853812e+00],
       [ 3.00966435e+03, -4.49301719e+03,  4.99996950e+00],
       ...,
       [ 2.22897839e+03,  1.09020803e+03,  6.56785894e-01],
       [ 2.30836705e+03,  1.32083186e+03,  6.58291131e-01],
       [ 2.35000094e+03,  1.28613619e+03,  6.57133695e-01]])

In [45]:
# same for velocity
# compute 3-D velocity from each host galaxy center along simulation's default x,y,z cartesian axes [km / s]

part['star'].prop('host.velocity')

array([[ 2708.9487  , -1166.6626  , -1409.9478  ],
       [ 2490.5488  ,    17.434566,  1405.2446  ],
       [  718.4118  ,   -58.166218,   320.6723  ],
       ...,
       [  -60.571285,  -188.28578 ,   -42.540314],
       [  -76.65155 ,  -212.06598 ,   -59.115223],
       [  -75.26818 ,  -215.50632 ,   -55.73956 ]], dtype=float32)

In [46]:
# compute total (scalar) velocity [km / s]

part['star'].prop('host.velocity.total')

array([3269.1677 , 2859.694  ,  788.87866, ...,  202.31187,  233.11382,
        234.9791 ], dtype=float32)

In [47]:
# compute 3-D velocity along the principal (major, intermediate, minor) axes [km / s]

part['star'].prop('host.velocity.principal')

array([[ 2162.648   , -2450.0674  ,    87.068085],
       [  913.85455 , -1216.1293  , -2421.518   ],
       [  324.02713 ,  -373.31314 ,  -614.7953  ],
       ...,
       [  151.06438 ,    89.74009 ,   100.281425],
       [  167.16342 ,   101.80418 ,   126.6268  ],
       [  170.782   ,   103.66906 ,   123.69885 ]], dtype=float32)

In [48]:
# compute 3-D velocity in cylindrical coordinates
# first value is along the major axes (positive definite)
# second value is vertical velocity wrt the disk (signed)
# third value is azimuthal velocity in the plane of the disk (positive definite)

part['star'].prop('host.velocity.principal.cylindrical')

array([[ 3.26789331e+03,  8.70680847e+01, -2.73782120e+01],
       [ 1.52121460e+03, -2.42151807e+03, -2.62215066e+00],
       [ 4.49887024e+02, -6.14795288e+02,  2.04836380e+02],
       ...,
       [ 1.74429779e+02,  1.00281425e+02, -2.11656170e+01],
       [ 1.94513092e+02,  1.26626801e+02, -2.17338371e+01],
       [ 1.98542267e+02,  1.23698853e+02, -2.22425785e+01]], dtype=float32)

In [49]:
# if you want to store multiple hosts (such as for the ELVIS LG-like paired simulations), 
# set host_number=2 during read-in
# (in fact, you can do this for any simulation, it simply finds the second most massive host galaxy in the full zoom-in region)

part = gizmo.io.Read.read_snapshots(['star', 'dark'], 'redshift', 0, simulation_directory, host_number=2, assign_host_principal_axes=True)


# in utilities.simulation.Snapshot():
* reading:  Users/awetzel/work/research/simulation/gizmo/simulations/m12/m12i/m12i_res7100/snapshot_times.txt

* input redshift = 0:  using snapshot index = 600, redshift = 0.000


# in gizmo_analysis.gizmo_io.Read():
* reading header from:  Users/awetzel/work/research/simulation/gizmo/simulations/m12/m12i/m12i_res7100/output/snapdir_600/snapshot_600.0.hdf5
  snapshot contains the following number of particles:
    dark      (id = 1): 70514272 particles
    dark2     (id = 2): 5513331 particles
    gas       (id = 0): 57060074 particles
    star      (id = 4): 13976485 particles
    blackhole (id = 5): 0 particles

* reading species: ['star', 'dark']
* reading particles from:
    snapshot_600.0.hdf5
    snapshot_600.1.hdf5
    snapshot_600.2.hdf5
    snapshot_600.3.hdf5

* reading cosmological parameters from:  Users/awetzel/work/research/simulation/gizmo/simulations/m12/m12i/m12i_res7100/initial_condition/ic_agora_m12i.conf

* checking sanity of 

In [50]:
# everything above still works, just use 'host', 'host2', 'host3', etc 
# to identify which host you want coordinates relative to

print(part['star'].prop('host.distance'))
print(part['star'].prop('host2.distance'))

[[ 24975.11425893 -10792.80189557 -12335.11771654]
 [  3983.54902862     25.40006428   2253.9448853 ]
 [  4785.81220605   1024.30854032   2300.45137017]
 ...
 [  -911.57152101  -2292.59980513   -264.42711553]
 [ -1040.99901548  -2408.21929041   -435.83956389]
 [ -1028.77197735  -2441.77486598   -394.98664985]]
[[ 25157.72510828 -10650.49268842 -12355.01895419]
 [  4166.15987796    167.70927142   2234.04364765]
 [  4968.42305539   1166.61774746   2280.55013252]
 ...
 [  -728.96067167  -2150.29059799   -284.32835318]
 [  -858.38816614  -2265.91008327   -455.74080154]
 [  -846.161128    -2299.46565884   -414.8878875 ]]


In [52]:
# gizmo_analysis stores coordinates and rotation tensors for each host

print(part.host_positions)
print(part.host_velocities)
print(part.host_rotations)

[[41792.14655358 44131.23458952 46267.67922214]
 [41609.53570424 43988.92538238 46287.58045979]]
[[-52.451195  71.85305   95.19773 ]
 [-96.2534   134.69872   55.539604]]
[[[ 0.38804234 -0.92127503 -0.02598965]
  [-0.78055724 -0.34350448  0.52224043]
  [-0.49005463 -0.18236499 -0.85240218]]

 [[ 0.8648546   0.09293337  0.49334562]
  [-0.1450857   0.98705152  0.06840641]
  [ 0.48060031  0.13073899 -0.86713935]]]


# star + gas particle tracking

Some simulations have pre-compiled HDF5 files for tracking star + gas particles over time. We store these files in the directory 'track/' (if present). gizmo_track.py contains the code that generates and reads these files.

star\_gas\_pointers\_\*.hdf5 files store, for each star and gas particles at z = 0, a pointer to where it was in the catalog at each previous snapshot (replace * with snapshot index). This makes it easy quickly to get the properties of a given star particle at any previous snapshot. We store these pointers in an HDF5 file, one for each previous snapshot.

### tracking between z = 0 and a previous snapshot

In [120]:
# read catalog of star and gas particles at z = 0

part_at_z0 = gizmo.io.Read.read_snapshots(['star', 'gas'], 'redshift', 0, simulation_directory)


# in utilities.simulation.Snapshot():
* reading:  Users/awetzel/work/research/simulation/gizmo/simulations/m12/m12i/m12i_res57000/snapshot_times.txt

* input redshift = 0:  using snapshot index = 600, redshift = 0.000


# in gizmo_analysis.gizmo_io.Read():
* reading header from:  Users/awetzel/work/research/simulation/gizmo/simulations/m12/m12i/m12i_res57000/output/snapshot_600.hdf5
  snapshot contains the following number of particles:
    dark      (id = 1): 8820344 particles
    dark2     (id = 2): 3081337 particles
    gas       (id = 0): 5969934 particles
    star      (id = 4): 3059250 particles
    blackhole (id = 5): 0 particles

* reading species: ['star', 'gas']
* reading particles from:
    Users/awetzel/work/research/simulation/gizmo/simulations/m12/m12i/m12i_res57000/output/snapshot_600.hdf5

* reading cosmological parameters from:  Users/awetzel/work/research/simulation/gizmo/simulations/m12/m12i/m12i_res57000/initial_condition/ic_agora_m12i.conf

* checking sanity of pa

In [121]:
# say that you want to find out what they were doing at z = 2
# read in catalog of star particles at z = 2 (probably snapshot 172)
# set assign_pointers=True to assign such pointers to the particle catalog at z = 2

part_at_z2 = gizmo.io.Read.read_snapshots(
    ['star', 'gas'], 'redshift', 2, simulation_directory, assign_pointers=True)


# in utilities.simulation.Snapshot():
* reading:  Users/awetzel/work/research/simulation/gizmo/simulations/m12/m12i/m12i_res57000/snapshot_times.txt

* input redshift = 2:  using snapshot index = 172, redshift = 2.000


# in gizmo_analysis.gizmo_io.Read():
* reading header from:  Users/awetzel/work/research/simulation/gizmo/simulations/m12/m12i/m12i_res57000/output/snapshot_172.hdf5
  snapshot contains the following number of particles:
    dark      (id = 1): 8820344 particles
    dark2     (id = 2): 3081337 particles
    gas       (id = 0): 8575137 particles
    star      (id = 4): 245223 particles
    blackhole (id = 5): 0 particles

* reading species: ['star', 'gas']
* reading particles from:
    Users/awetzel/work/research/simulation/gizmo/simulations/m12/m12i/m12i_res57000/output/snapshot_172.hdf5

* reading cosmological parameters from:  Users/awetzel/work/research/simulation/gizmo/simulations/m12/m12i/m12i_res57000/initial_condition/ic_agora_m12i.conf

* checking sanity of par

In [122]:
# we store particle pointers via a dictionary class appended to particle catalog dictionary at the relevant snapshot
# a negative value means that the star formed after this snapshot (so it does not exist at this snapshot)

part_at_z2.Pointer

{'species': array(['star', 'gas'], dtype='<U4'),
 'z.gas.index.limits': array([ 245223, 8820360]),
 'z.gas.number': 8575137,
 'z.particle.number': 8820360,
 'z.snapshot.index': 172,
 'z.star.index.limits': array([     0, 245223]),
 'z.star.number': 245223,
 'z0.gas.index.limits': array([3059250, 9029184]),
 'z0.gas.number': 5969934,
 'z0.particle.number': 9029184,
 'z0.snapshot.index': 600,
 'z0.star.index.limits': array([      0, 3059250]),
 'z0.star.number': 3059250,
 'z0.to.z.index': array([8762407, 6627790, 2897974, ...,  428042, 1883434, 1569509],
       dtype=int32)}

In [123]:
# the particle species that we have compiled tracking pointers for

part_at_z2.Pointer['species']

array(['star', 'gas'], dtype='<U4')

In [125]:
# the snapshot indices at this redshift (z = 2) and at the reference redshift (z = 0)

print(part_at_z2.Pointer['z.snapshot.index'])
print(part_at_z2.Pointer['z0.snapshot.index'])

172
600


In [126]:
# the number of particles at this redshift (z = 2) and at the reference redshift (z = 0)

print(part_at_z2.Pointer['z.star.number'])
print(part_at_z2.Pointer['z.gas.number'])

print(part_at_z2.Pointer['z0.star.number'])
print(part_at_z2.Pointer['z0.gas.number'])

245223
8575137
3059250
5969934


In [127]:
# the dictionaries below store the actual pointer indices
# becase gas particles can become star particles, this pipeline concatenates the particle list and 
# stores pointers from this combined star + gas list at z = 0 to z

print(part_at_z2.Pointer['z0.to.z.index'])

# this also stores the limits of the indices of each species at each snapshot, 
# so you can convert back to the index within the individual star list or the individual gas list 
# (as stored in the particle catalog)
print(part_at_z2.Pointer['z.star.index.limits'])
print(part_at_z2.Pointer['z.gas.index.limits'])

print(part_at_z2.Pointer['z0.star.index.limits'])
print(part_at_z2.Pointer['z0.gas.index.limits'])

[8762407 6627790 2897974 ...  428042 1883434 1569509]
[     0 245223]
[ 245223 8820360]
[      0 3059250]
[3059250 9029184]


In [128]:
# more simply, you can use this function to get pointers for a given species from z = 0 to any z
# the default mode of tracking is going backward in time (from z = 0 to z)

pointers = part_at_z2.Pointer.get_pointers(species_name_from='star', species_names_to='star')

In [129]:
# say that you have a list of star particle indices of interest at z = 0

indices_at_z0 = np.array([5, 8, 13])

# list their positions at z = 0

part_at_z0['star']['position'][indices_at_z0]

array([[43395.66430266, 44225.91487342, 46848.42028784],
       [43391.32501013, 44235.3333939 , 46851.26898524],
       [43392.7246372 , 44234.88455716, 46860.08437896]])

In [130]:
# now you can get their indices in the particle catalog at z = 2
# negative indices means that the star particle did not exist at z = 2

indices_at_z2 = pointers[indices_at_z0]
print(indices_at_z2)

# now you easily can get any property of interest at z = 2, for example, positions
part_at_z2['star']['position'][indices_at_z2]

[93570 93569 93574]


array([[44594.70662236, 42857.76681624, 45680.41942321],
       [44597.17009857, 42856.9103464 , 45683.54318435],
       [44586.14301487, 42869.01990286, 45673.47361522]])

In [131]:
# alternatively, you can track particles going forward in time by setting forward=True

pointers = part_at_z2.Pointer.get_pointers(species_name_from='star', species_names_to='star', forward=True)

indices_at_z2 = np.array([5, 8, 13])
indices_at_z0 = pointers[indices_at_z2]
print(indices_at_z0)
print(part_at_z0['star']['position'][indices_at_z0])

[1081507 2621944 1378523]
[[41827.95243832 44124.6273934  46289.64224645]
 [41810.05286106 44110.48518841 46285.84784929]
 [41827.05895642 44116.02070015 46284.00376819]]


In [132]:
# also, you can track star particles back to both progenitor star and progenitor gas particles

pointers = part_at_z2.Pointer.get_pointers(species_name_from='star', species_names_to=['star', 'gas'])

# but now, pointers is a *dictionary* that stores both the index and species of each progenitor particle
print(pointers)

# get star particle indices at z = 0 and see what they were at z = 2
star_indices_at_z0 = np.array([0, 5, 8, 13])
print(pointers['species'][star_indices_at_z0], pointers['index'][star_indices_at_z0])

# get those that were gas particles
masks = np.where(pointers['species'][star_indices_at_z0] == 'gas')[0]

gas_indices_at_z2 = pointers['index'][star_indices_at_z0[masks]]

print(gas_indices_at_z2)
print(part_at_z2['gas']['position'][gas_indices_at_z2])

{'index': array([8517184, 6382567, 2652751, ..., 5870729,  297634,  179265],
      dtype=int32), 'species': array(['gas', 'gas', 'gas', ..., 'gas', 'gas', 'star'], dtype='<U4')}
['gas' 'star' 'star' 'star'] [8517184   93570   93569   93574]
[8517184]
[[42845.52824108 42506.12287672 44870.50121988]]


In [133]:
# similar for working forward in time, track gas particles at z that can be star or gas particles at z = 0

pointers = part_at_z2.Pointer.get_pointers(
    species_name_from='gas', species_names_to=['star', 'gas'], forward=True)

# get gas indices at z = 2 and see what they end up as at z = 0
gas_indices_at_z2 = np.array([0, 5, 8, 13])
print(pointers['species'][gas_indices_at_z2])
print(pointers['index'][gas_indices_at_z2])

# get those that are star particles at z = 0
masks = np.where(pointers['species'][gas_indices_at_z2] == 'star')[0]

star_indices_at_z0 = pointers['index'][gas_indices_at_z2[masks]]

print(star_indices_at_z0)
print(part_at_z0['star']['position'][star_indices_at_z0])

['star' 'star' 'gas' 'gas']
[ 215205 1917430 1826927 4148144]
[ 215205 1917430]
[[41823.76116895 44122.68646199 46287.49155757]
 [41813.98704585 44118.76742237 46303.17274406]]


### tracking between 2 snapshots in which both are at z > 0

In [134]:
# particle tracking also can handle tracking particles between any 2 snapshots

# read catalogs of star and gas particles at z = 1 and 2, including their pointers relative to z = 0
# set asign_pointers=True automatically to append pointer class to each particle catalog
part_at_z1 = gizmo.io.Read.read_snapshots(
    ['star', 'gas'], 'redshift', 1, simulation_directory, assign_pointers=True)
part_at_z2 = gizmo.io.Read.read_snapshots(
    ['star', 'gas'], 'redshift', 2, simulation_directory, assign_pointers=True)


# in utilities.simulation.Snapshot():
* reading:  Users/awetzel/work/research/simulation/gizmo/simulations/m12/m12i/m12i_res57000/snapshot_times.txt

* input redshift = 1:  using snapshot index = 277, redshift = 1.000


# in gizmo_analysis.gizmo_io.Read():
* reading header from:  Users/awetzel/work/research/simulation/gizmo/simulations/m12/m12i/m12i_res57000/output/snapshot_277.hdf5
  snapshot contains the following number of particles:
    dark      (id = 1): 8820344 particles
    dark2     (id = 2): 3081337 particles
    gas       (id = 0): 7498674 particles
    star      (id = 4): 1333580 particles
    blackhole (id = 5): 0 particles

* reading species: ['star', 'gas']
* reading particles from:
    Users/awetzel/work/research/simulation/gizmo/simulations/m12/m12i/m12i_res57000/output/snapshot_277.hdf5

* reading cosmological parameters from:  Users/awetzel/work/research/simulation/gizmo/simulations/m12/m12i/m12i_res57000/initial_condition/ic_agora_m12i.conf

* checking sanity of pa

In [135]:
# now just append intermediate-redshift pointers (to z = 1) to pointers at z = 2

part_at_z2.Pointer.add_intermediate_pointers(part_at_z1.Pointer)

In [136]:
# now you can access pointers from z = 1 to z = 2, by setting intermediate_snapshot=True

pointers = part_at_z2.Pointer.get_pointers(
    species_name_from='star', species_names_to=['star', 'gas'], intermediate_snapshot=True)

# get star indices at z = 0 and see what they were at z = 2
star_indices_at_z1 = np.array([0, 5, 8, 13])
print(pointers['species'][star_indices_at_z1])
print(pointers['index'][star_indices_at_z1])

# get those that are star particles at z = 2
masks = np.where(pointers['species'][star_indices_at_z1] == 'star')[0]

star_indices_at_z2 = pointers['index'][star_indices_at_z1[masks]]

print(star_indices_at_z2)
print(part_at_z2['star']['position'][star_indices_at_z2])

['star' 'gas' 'gas' 'gas']
[ 107166 1169600 6377478  239484]
[107166]
[[43535.53900573 42053.83122207 46265.70989359]]


In [138]:
# if you just want to track a single species (star -> star or gas -> gas) between 2 snapshots,
# read_pointers_between_snapshots() makes it easy to get the pointer indices between any 2 snapshots

ParticlePointer = gizmo.track.ParticlePointerClass(simulation_directory=simulation_directory)

# tracking forward in time
pointers_z2_to_z1 = ParticlePointer.read_pointers_between_snapshots(
    snapshot_index_from=172, snapshot_index_to=277, species_name='star')

# for example, see how far star particles have moved
print(part_at_z2['star']['position'] - part_at_z1['star']['position'][pointers_z2_to_z1])


# similar for tracking going backward in time
pointers_z1_to_z2 = ParticlePointer.read_pointers_between_snapshots(
    snapshot_index_from=277, snapshot_index_to=172, species_name='star')

# in this case, need to select stars that existed as stars at z = 2
masks = (pointers_z1_to_z2 >= 0)

# see how far star particles have moved
print(part_at_z1['star']['position'][masks] - part_at_z1['star']['position'][pointers_z1_to_z2[masks]])


# in utilities.basic.io.file_hdf5():
  read file: star_gas_pointers_277.hdf5
    species | |S4, shape = (2,)
    z.gas.index.limits | int64, shape = (2,)
    z.gas.number | int64, shape = ()
    z.particle.number | int64, shape = ()
    z.snapshot.index | int64, shape = ()
    z.star.index.limits | int64, shape = (2,)
    z.star.number | int64, shape = ()
    z0.gas.index.limits | int64, shape = (2,)
    z0.gas.number | int64, shape = ()
    z0.particle.number | int64, shape = ()
    z0.snapshot.index | int64, shape = ()
    z0.star.index.limits | int64, shape = (2,)
    z0.star.number | int64, shape = ()
    z0.to.z.index | int32, shape = (9029184,)

# in utilities.basic.io.file_hdf5():
  read file: star_gas_pointers_172.hdf5
    species | |S4, shape = (2,)
    z.gas.index.limits | int64, shape = (2,)
    z.gas.number | int64, shape = ()
    z.particle.number | int64, shape = ()
    z.snapshot.index | int64, shape = ()
    z.star.index.limits | int64, shape = (2,)
    z.star.number |

In [139]:
# do the same, but for gas

ParticlePointer = gizmo.track.ParticlePointerClass(simulation_directory=simulation_directory)

# tracking going forward in time
pointers_z2_to_z1 = ParticlePointer.read_pointers_between_snapshots(
    snapshot_index_from=172, snapshot_index_to=277, species_name='gas')

# ensure that gas particle still is a gas particle at z = 1
masks = (pointers_z2_to_z1 >= 0)

print(part_at_z2['gas']['position'][masks] - part_at_z1['gas']['position'][pointers_z2_to_z1[masks]])

# tracking going backward in time
pointers_z1_to_z2 = ParticlePointer.read_pointers_between_snapshots(
    snapshot_index_from=277, snapshot_index_to=172, species_name='gas')

# for gas, still have to ensure positive pointers, even if tracking going backward in time,
# because a few gas particles that leave the zoom-in region get culled (for numerical stability) by z = 0
# (remember that the pointers always route through z = 0)
masks = (pointers_z1_to_z2 >= 0)

print(part_at_z1['gas']['position'][masks] - part_at_z2['gas']['position'][pointers_z1_to_z2[masks]])


# in utilities.basic.io.file_hdf5():
  read file: star_gas_pointers_277.hdf5
    species | |S4, shape = (2,)
    z.gas.index.limits | int64, shape = (2,)
    z.gas.number | int64, shape = ()
    z.particle.number | int64, shape = ()
    z.snapshot.index | int64, shape = ()
    z.star.index.limits | int64, shape = (2,)
    z.star.number | int64, shape = ()
    z0.gas.index.limits | int64, shape = (2,)
    z0.gas.number | int64, shape = ()
    z0.particle.number | int64, shape = ()
    z0.snapshot.index | int64, shape = ()
    z0.star.index.limits | int64, shape = (2,)
    z0.star.number | int64, shape = ()
    z0.to.z.index | int32, shape = (9029184,)

# in utilities.basic.io.file_hdf5():
  read file: star_gas_pointers_172.hdf5
    species | |S4, shape = (2,)
    z.gas.index.limits | int64, shape = (2,)
    z.gas.number | int64, shape = ()
    z.particle.number | int64, shape = ()
    z.snapshot.index | int64, shape = ()
    z.star.index.limits | int64, shape = (2,)
    z.star.number |

# star particle formation coordinates

As part of star particle tracking, we store the position and velocity of each star particle immediately after it formed.

Within track/, star\_form\_coordinates\_600.hdf5 stores, for each star particle at z = 0, its 3-D distance and 3-D velocity wrt to the main host galaxy at the first snapshot after it formed. These coordinates are aligned with the principal (major, intermediate, minor) axes of the stellar disk (as defined via its moment of inertia tensor) at that snapshot.

In [140]:
# use the function within gizmo_track.py to read this file and assign values directly to the catalog at z = 0

gizmo.track.ParticleCoordinate.io_formation_coordinates(part_at_z0, simulation_directory)


# in utilities.basic.io.file_hdf5():
  read file: star_form_coordinates_600.hdf5
    center.position | float32, shape = (601, 3)
    center.velocity | float32, shape = (601, 3)
    form.host.distance | float32, shape = (3059250, 3)
    form.host.velocity | float32, shape = (3059250, 3)
    id | uint32, shape = (3059250,)
    principal.axes.vectors | float32, shape = (601, 3, 3)


In [156]:
# more conveniently, you can read the formation coordinates of star particles during snapshot read-in
# by setting assign_formation_coordinates=True

part_at_z0 = gizmo.io.Read.read_snapshots(
    ['star'], 'redshift', 0, simulation_directory, assign_host_principal_axes=True, 
    assign_formation_coordinates=True)


# in utilities.simulation.Snapshot():
* reading:  Users/awetzel/work/research/simulation/gizmo/simulations/m12/m12i/m12i_res57000/snapshot_times.txt

* input redshift = 0:  using snapshot index = 600, redshift = 0.000


# in gizmo_analysis.gizmo_io.Read():
* reading header from:  Users/awetzel/work/research/simulation/gizmo/simulations/m12/m12i/m12i_res57000/output/snapshot_600.hdf5
  snapshot contains the following number of particles:
    dark      (id = 1): 8820344 particles
    dark2     (id = 2): 3081337 particles
    gas       (id = 0): 5969934 particles
    star      (id = 4): 3059250 particles
    blackhole (id = 5): 0 particles

* reading species: ['star']
* reading particles from:
    Users/awetzel/work/research/simulation/gizmo/simulations/m12/m12i/m12i_res57000/output/snapshot_600.hdf5

* reading cosmological parameters from:  Users/awetzel/work/research/simulation/gizmo/simulations/m12/m12i/m12i_res57000/initial_condition/ic_agora_m12i.conf

* checking sanity of particle 

In [142]:
# 3-D distance at formation
# this is aligned with the principal axes of each host galaxy at that time [kpc physical]
# we compute the principal axes *independently* at each snapshot
# distance along dimension 0 is aligned with the major axis
# distance along dimension 1 is algined with the intermediate axis
# distance along dimension 2 is aligned with the minor (Z) axis

part_at_z0['star']['form.host.distance']

# part_at_z0['star']['form.host2.distance']  # if the simulation has a second host galaxy (for example, ELVIS)

array([[    3.8351834,     6.170289 ,    -1.4488623],
       [  951.6061   , -1143.819    ,   541.5925   ],
       [ 1258.5391   ,   183.60645  ,   -92.80096  ],
       ...,
       [  542.5843   ,  -580.9797   ,   927.32684  ],
       [ -376.8372   ,   349.8039   ,  -245.89764  ],
       [ -275.3792   ,   -35.97139  ,  -272.96063  ]], dtype=float32)

In [143]:
# as before, add 'total' to get the total scalar (absolute) distance wrt each host galaxy at formation [kpc physical]
# this is a derived quantity, so need to call via .prop()

part_at_z0['star'].prop('form.host.distance.total')

array([   7.408124, 1583.4136  , 1275.2427  , ..., 1221.4214  ,
        569.9427  ,  389.4036  ], dtype=float32)

In [144]:
# add 'cylindrical' to get 3-D distance at formation wrt each host galaxy in cylindrical coordinates [kpc physical]

part_at_z0['star'].prop('form.host.distance.cylindrical')

array([[ 7.2650599e+00, -1.4488623e+00,  1.0146770e+00],
       [ 1.4879099e+03,  5.4159253e+02,  5.4063134e+00],
       [ 1.2718616e+03, -9.2800957e+01,  1.4486657e-01],
       ...,
       [ 7.9494348e+02,  9.2732684e+02,  5.4636278e+00],
       [ 5.1416827e+02, -2.4589764e+02,  2.3933804e+00],
       [ 2.7771866e+02, -2.7296063e+02,  3.2714822e+00]], dtype=float32)

In [145]:
# these values look more reasonable if you restrict to star particles that formed within a host galaxy

# select particles formed at d = 0 - 8 kpc physical
part_indices = ut.array.get_indices(part_at_z0['star'].prop('form.host.distance.total'), [0, 8])

part_at_z0['star'].prop('form.host.distance.cylindrical', part_indices)

array([[ 7.26506   , -1.4488623 ,  1.014677  ],
       [ 2.819624  , -0.01174179,  4.65897   ],
       [ 2.4207215 , -0.02199288,  3.6387615 ],
       ...,
       [ 2.7438505 , -1.4894025 ,  5.987568  ],
       [ 3.6302092 , -0.01234316,  3.3655412 ],
       [ 1.5276729 , -0.12618025,  1.8085258 ]], dtype=float32)

In [153]:
# same for velocity at formation

print(part_at_z0['star']['form.host.velocity'])
print(part_at_z0['star'].prop('form.host.velocity.total'))
print(part_at_z0['star'].prop('form.host.velocity.cylindrical'))

[[ 5.10321930e+02  8.53348755e+02  2.34322433e+02]
 [ 4.29511480e-02 -1.29415512e+02  3.22944736e+00]
 [ 1.82360718e+02 -1.09645996e+02  3.08418255e+01]
 ...
 [ 3.11529217e+01 -1.06510910e+02 -1.64038372e+00]
 [-9.91549301e+01 -8.34163761e+00  2.34269543e+01]
 [-1.11417809e+02  4.18189201e+01 -2.22872696e+01]]
[1021.5379   129.45581  215.00905 ...  110.98545  102.22575  121.07631]
[[ 994.1538     234.32243     17.056305 ]
 [  99.514626     3.2294474  -82.735825 ]
 [ 164.622       30.841825  -134.82314  ]
 ...
 [  99.10612     -1.6403837  -49.930504 ]
 [  66.996216    23.426954    73.57168  ]
 [ 105.06267    -22.28727    -55.897987 ]]


In [159]:
# recall that we store formation postions + velocities relative to each host's principal axes
# and that we compute the principal axes separately at each snapshot
# thus, we also store each host's coordinates and rotation tensor (for its principal axes) at each snapshot
# so you can use this to compute formation coordinates in the box's x,y,z coordinates if you want

print(part_at_z0.host_positions_all)
print(part_at_z0.host_velocities_all)
print(part_at_z0.host_rotations_all)

[[      nan       nan       nan]
 [      nan       nan       nan]
 [      nan       nan       nan]
 ...
 [41822.16  44121.64  46287.992]
 [41822.08  44121.836 46288.242]
 [41821.973 44122.004 46288.457]]
[[       nan        nan        nan]
 [       nan        nan        nan]
 [       nan        nan        nan]
 ...
 [-48.60276   73.29304   96.20622 ]
 [-48.64333   73.259476  96.438835]
 [-48.736935  73.20865   96.66936 ]]
[[[        nan         nan         nan]
  [        nan         nan         nan]
  [        nan         nan         nan]]

 [[        nan         nan         nan]
  [        nan         nan         nan]
  [        nan         nan         nan]]

 [[        nan         nan         nan]
  [        nan         nan         nan]
  [        nan         nan         nan]]

 ...

 [[-0.23860915  0.24924965  0.9385842 ]
  [ 0.8640545   0.49563974  0.08804033]
  [-0.4432556   0.83199507 -0.33362946]]

 [[-0.01853178  0.36362258  0.93136203]
  [ 0.8962332   0.418959   -0.14573726]


# profile of properties

A common task is to compute a radial profile of a given quantity, such as mass density, average age, median metallicity, etc.

The high-level functions below make this easier to do.

In [182]:
# read star particles at z = 0

part = gizmo.io.Read.read_snapshots(
    ['star'], 'redshift', 0, simulation_directory, assign_host_principal_axes=True)


# in utilities.simulation.Snapshot():
* reading:  Users/awetzel/work/research/simulation/gizmo/simulations/m12/m12i/m12i_res57000/snapshot_times.txt

* input redshift = 0:  using snapshot index = 600, redshift = 0.000


# in gizmo_analysis.gizmo_io.Read():
* reading header from:  Users/awetzel/work/research/simulation/gizmo/simulations/m12/m12i/m12i_res57000/output/snapshot_600.hdf5
  snapshot contains the following number of particles:
    dark      (id = 1): 8820344 particles
    dark2     (id = 2): 3081337 particles
    gas       (id = 0): 5969934 particles
    star      (id = 4): 3059250 particles
    blackhole (id = 5): 0 particles

* reading species: ['star']
* reading particles from:
    Users/awetzel/work/research/simulation/gizmo/simulations/m12/m12i/m12i_res57000/output/snapshot_600.hdf5

* reading cosmological parameters from:  Users/awetzel/work/research/simulation/gizmo/simulations/m12/m12i/m12i_res57000/initial_condition/ic_agora_m12i.conf

* checking sanity of particle 

In [183]:
# first, initiate an instance of SpeciesProfileClass
# as you initialize, choose your distance/radius binning scheme:
#   'log' v 'linear', distance limits, bin width, number of spatial dimensions of profile
# refer to ut.binning.DistanceBinClass() for more

# linear binning from 0 to 20 kpc with 1 kpc bin width, assuming a 3-D profile
SpeciesProfile = ut.particle.SpeciesProfileClass(
    scaling='linear', limits=[0, 20], width=1, dimension_number=3)

In [184]:
# using this binning scheme,
# compute sum/histogram/density of mass of star particles in each bin
# this returns a bunch of summed properties via a dictionary

pro = SpeciesProfile.get_sum_profiles(part, 'star', 'mass')


# in utilities.particle.SpeciesProfile():
  input  3059250 distances -  2706222 (88.5%) are within limits = [0.000, 20.000]


In [185]:
# you can supply a list of multiple species, and it will compute profiles for each
# thus, it returns a dictionary for each species

pro.keys()

dict_keys(['star', 'baryon', 'total'])

In [186]:
# the quantities that it stores in each bin

pro['star'].keys()

dict_keys(['sum', 'sum.cum', 'log sum', 'log sum.cum', 'density', 'log density', 'density.cum', 'log density.cum', 'density*r', 'log density*r', 'density*r^2', 'log density*r^2', 'distance.mid', 'distance.cum', 'log distance.mid', 'log distance.cum', 'sum.fraction', 'sum.cum.fraction', 'vel.circ'])

In [187]:
# alternately, you may want to compute profiles along a disk's cylindrical R or Z axes
# if so, first define the dimensionality of the profile when you initiate the class

# log binning from 0.1 to 10 kpc with 0.1 dex bin width, assuming a 2-D profile (along R)
SpeciesProfile = ut.particle.SpeciesProfileClass(
    scaling='log', limits=[0.1, 10], width=0.1, dimension_number=2)

In [188]:
# set rotation=True to force the code to compute profiles along the principal axes (assuming that you read them in)
# use other_axis_distance_limits to limit the extent along the other axis, 
#   in this case, limit the Z axis to within +/- 1 kpc (in the profile, all distances are absolute)

pro = SpeciesProfile.get_sum_profiles(
    part, 'star', 'mass', rotation=True, other_axis_distance_limits=[0, 1])


# in utilities.particle.SpeciesProfile():
  input  2097166 distances -  2064222 (98.4%) are within limits = [0.100, 10.000]


In [189]:
# similarly, do this to compute profiles along disk's Z axis

# log binning from 0.1 to 10 kpc with 0.1 dex bin width, assuming a 1-D profile (along Z)
SpeciesProfile = ut.particle.SpeciesProfileClass(
    scaling='log', limits=[0.1, 10], width=0.1, dimension_number=1)

# limit the R axex to [5, 8] kpc 
pro = SpeciesProfile.get_sum_profiles(
    part, 'star', 'mass', rotation=True, other_axis_distance_limits=[5, 8])


# in utilities.particle.SpeciesProfile():
  input   293273 distances -   259637 (88.5%) are within limits = [0.100, 10.000]


In [191]:
# using the same binning scheme
# this function computes various statistics of a property of star particles in each bin
# below, it  weights the property by the mass of each star particle (generally what you should do)
# this returns a bunch of useful statistics via a dictionary

pro = SpeciesProfile.get_statistics_profiles(
    part, 'star', 'age', weight_by_mass=True, rotation=True, other_axis_distance_limits=[5, 8])

input   293273 distances -   259637 (88.5%) are within limits = [0.100, 10.000]


In [192]:
# the quantities that it stores in each bin

pro['star'].keys()

dict_keys(['limits', 'number', 'median', 'percent.16', 'percent.84', 'percent.2', 'percent.98', 'percent.0.1', 'percent.99.9', 'percent.25', 'percent.75', 'percents.68', 'percents.95', 'median.dif.2', 'median.dif.16', 'median.dif.84', 'median.dif.98', 'median.difs.68', 'median.difs.95', 'average', 'std', 'sem', 'std.lo', 'std.hi', 'min', 'max', 'percent.50', 'average.50', 'sem.lo', 'sem.hi', 'distance.mid', 'distance.cum', 'log distance.mid', 'log distance.cum'])