First, move within a simulation directory. This directory should contains the sub-directory 'output/' that contains snapshot files, and a file 'snapshot_times.txt' that lists all snapshot scale-factors/redshifts/times in the simulation and their corresponding file index number.

Ensure that gizmo_analysis and utilities directories are in your python path, then...

In [1]:
import gizmo_analysis as gizmo
import utilities as ut

In [2]:
# you can access the files as named or use the aliases in __init__.py to keep it shorter 
# for example, these are the same:

gizmo.gizmo_io
gizmo.io

<module 'gizmo_analysis.gizmo_io' from '/Users/awetzel/work/research/analysis/gizmo_analysis/gizmo_io.py'>

# read particle data

In [3]:
# read star and dark matter particles at z = 0

part = gizmo.io.Read.read_snapshots(['star', 'dark'], 'redshift', 0)


# in utilities.simulation.Snapshot():
  reading:  snapshot_times.txt
  input redshift = 0:  using snapshot index = 600, redshift = 0.000


# in gizmo_analysis.gizmo_io.Read():
* reading header from:  output/snapshot_600.hdf5
  snapshot contains the following number of particles:
    dark      (id = 1): 8820344 particles
    dark2     (id = 2): 3081337 particles
    gas       (id = 0): 5969934 particles
    star      (id = 4): 3059250 particles
    blackhole (id = 5): 0 particles

* reading species: ['star', 'dark']
* reading particles from:
    output/snapshot_600.hdf5

* reading cosmological parameters from:  initial_condition/ic_agora_m12i.conf

* checking sanity of particle properties

* assigning coordinates of host galaxy[s]/halo[s]:
  position = (41821.974, 44122.005, 46288.448) [kpc comoving]
  velocity = (-48.7, 73.2, 96.7) [km / s]



In [4]:
# alternately, read all particle species at z = 0

part = gizmo.io.Read.read_snapshots('all', 'redshift', 0)


# in utilities.simulation.Snapshot():
  reading:  snapshot_times.txt
  input redshift = 0:  using snapshot index = 600, redshift = 0.000


# in gizmo_analysis.gizmo_io.Read():
* reading header from:  output/snapshot_600.hdf5
  snapshot contains the following number of particles:
    dark      (id = 1): 8820344 particles
    dark2     (id = 2): 3081337 particles
    gas       (id = 0): 5969934 particles
    star      (id = 4): 3059250 particles
    blackhole (id = 5): 0 particles

* reading species: ['dark', 'dark2', 'gas', 'star']
* reading particles from:
    output/snapshot_600.hdf5

* reading cosmological parameters from:  initial_condition/ic_agora_m12i.conf

* checking sanity of particle properties

* assigning coordinates of host galaxy[s]/halo[s]:
  position = (41821.974, 44122.005, 46288.448) [kpc comoving]
  velocity = (-48.7, 73.2, 96.7) [km / s]



In [ ]:
# this tutorial assumes that you are in the root directory of a simulation, 
# but you can read a simulation at any location using input argument 'simulation_directory'

part = gizmo.io.Read.read_snapshots('all', 'redshift', 0, simulation_directory='/arb/it/rary/loc/a/tion')

In [5]:
# each particle species is stored as its own dictionary
# 'star' = stars, 'gas' = gas, 'dark' = dark matter, 'dark.2', 'dark.3', etc = low-resolution dark matter

part.keys()

dict_keys(['dark', 'dark2', 'gas', 'star'])

In [6]:
# properties of star particles are stored as dictionary

part['star'].keys()

dict_keys(['position', 'mass', 'massfraction', 'id.child', 'id.generation', 'id', 'potential', 'form.scalefactor', 'velocity'])

In [7]:
# properties of dark matter particles

part['dark'].keys()

dict_keys(['position', 'mass', 'id.child', 'id.generation', 'id', 'potential', 'velocity'])

In [8]:
# properties of gas particles

part['gas'].keys()

dict_keys(['position', 'density', 'electron.fraction', 'temperature', 'mass', 'massfraction', 'hydrogen.neutral.fraction', 'id.child', 'id.generation', 'id', 'potential', 'smooth.length', 'sfr', 'velocity'])

# particle properties

In [9]:
# 3-D position of star particle (particle number x dimension number) [kpc comoving]

part['star']['position']

array([[43090.80575884, 49686.35374503, 41360.34283508],
       [44928.29340924, 46498.85693528, 41973.80607722],
       [44165.06982706, 45905.57328081, 47149.21746307],
       ...,
       [41959.19387506, 42547.66435227, 46108.83355536],
       [41959.30623868, 42547.42814527, 46108.97969497],
       [41959.30737559, 42547.08535602, 46108.55536859]])

In [10]:
# 3-D velocity of star particle (particle number x dimension number) [km / s]

part['star']['velocity']

array([[  15.888516,  364.97275 , -154.04498 ],
       [ 172.60747 ,   55.058994, -366.62854 ],
       [ 126.053955,   -8.004937,  121.11193 ],
       ...,
       [ -54.528496,   93.02893 ,  -25.309298],
       [ -51.983   ,   31.671635,  -23.940857],
       [ -80.71081 ,   96.28201 ,   -8.430067]], dtype=float32)

In [11]:
# mass of star particle [M_sun]

part['star']['mass']

array([62936.75 , 48761.668, 39828.047, ..., 41346.055, 38390.59 ,
       37466.387], dtype=float32)

In [12]:
# formation scale-factor of star particle

part['star']['form.scalefactor']

array([0.46287337, 0.5831701 , 0.46225446, ..., 0.77500224, 0.4109269 ,
       0.321905  ], dtype=float32)

In [13]:
# use .prop() to compute derived quantities,
# such as the time [Gyr] when a star particle formed
# see gizmo.io.ParticleDictionaryClass for all options for derived quantities

part['star'].prop('form.time')

array([ 5.38456731,  7.35609019,  5.37457175, ..., 10.46071958,
        4.55585177,  3.20527164])

In [14]:
# similarly, get the age of a star particle (the lookback time to when it formed) [Gyr]

part['star'].prop('age')

array([ 8.41417957,  6.44265669,  8.42417513, ...,  3.3380273 ,
        9.24289511, 10.59347525])

# elemental abundance / metallicity

In [15]:
# elemental abundance is stored in the catalog as *linear mass fraction*
# one value for each element, in a array (particle_number x element number)
# the first value is the mass fraction of all metals (everything not H, He)
# then He, C, N, O, etc

part['star']['massfraction']

array([[2.28875540e-02, 2.73702413e-01, 3.47784720e-03, ...,
        5.18469051e-07, 2.59994462e-08, 5.13290921e-08],
       [9.04264394e-03, 2.58452922e-01, 1.16026576e-03, ...,
        2.35843927e-07, 1.29876696e-08, 2.13728626e-08],
       [4.13827086e-03, 2.53816098e-01, 5.14813582e-04, ...,
        1.17386868e-07, 1.05656595e-08, 1.46085215e-08],
       ...,
       [6.35253172e-03, 2.56642282e-01, 9.32708848e-04, ...,
        1.83839319e-07, 1.09649676e-08, 1.77075563e-08],
       [2.31894082e-03, 2.52064943e-01, 2.74994469e-04, ...,
        5.56808217e-08, 4.70536632e-09, 6.90510316e-09],
       [2.00070604e-03, 2.52106518e-01, 2.88566429e-04, ...,
        4.50247768e-08, 1.88898119e-09, 3.96916411e-09]], dtype=float32)

In [16]:
# get individual elements by their index

# total metal mass fraction (everything not H, He) is index 0
print(part['star']['massfraction'][:, 0])

# iron is index 10
print(part['star']['massfraction'][:, 10])

[0.02288755 0.00904264 0.00413827 ... 0.00635253 0.00231894 0.00200071]
[8.5570500e-04 4.0123638e-04 1.7354584e-04 ... 2.8746785e-04 9.2642935e-05
 7.1826209e-05]


In [17]:
# alternately use .prop() to compute derived quantities,
# including calling element by its name or symbol
# see gizmo.io.ParticleDictionaryClass for all options for derived quantities

print(part['star'].prop('massfraction.metals'))
print(part['star'].prop('massfraction.carbon'))
print(part['star'].prop('massfraction.iron'))
print(part['star'].prop('massfraction.fe'))  # can use name or symbol

[0.02288755 0.00904264 0.00413827 ... 0.00635253 0.00231894 0.00200071]
[0.00347785 0.00116027 0.00051481 ... 0.00093271 0.00027499 0.00028857]
[8.5570500e-04 4.0123638e-04 1.7354584e-04 ... 2.8746785e-04 9.2642935e-05
 7.1826209e-05]
[8.5570500e-04 4.0123638e-04 1.7354584e-04 ... 2.8746785e-04 9.2642935e-05
 7.1826209e-05]


In [18]:
# also use .prop() to compute metallicity [Z/H]
# for example, iron abundance [Fe/H] :=
#   log10((mass_iron / mass_hydrogen)_particle / (mass_iron / mass_hydrogen)_sun)
# my pipeline assumes solar abundances from Asplund et al 2009

print(part['star'].prop('metallicity.total'))
print(part['star'].prop('metallicity.fe'))

[ 0.23249461 -0.17080936 -0.5102859  ... -0.32415795 -0.76181513
 -0.8259215 ]
[-0.17933045 -0.50825423 -0.8722403  ... -0.65306526 -1.1448423
 -1.2553716 ]


In [19]:
# also use .prop() to compute simple arithmetic combinations, such as [Mg/Fe]

part['star'].prop('metallicity.mg - metallicity.fe')

array([0.31506985, 0.2700966 , 0.29745406, ..., 0.2505798 , 0.3211267 ,
       0.35478264], dtype=float32)

In [20]:
# refer to utilities.basic.constant for assumed solar values (Asplund et al 2009) and other constants

ut.constant.sun_composition

{'hydrogen': {'massfraction': 0.7381},
 'helium': {'abundance': 0.08511380382023759, 'massfraction': 0.2485},
 'metals': {'massfraction': 0.0134},
 'total': {'massfraction': 0.0134},
 'carbon': {'abundance': 0.0002691534803926914,
  'massfraction': 0.002367134813394483},
 'nitrogen': {'abundance': 6.760829753919819e-05,
  'massfraction': 0.0006934106379733354},
 'oxygen': {'abundance': 0.0004897788193684457,
  'massfraction': 0.005737971271592906},
 'neon': {'abundance': 8.51138038202376e-05,
  'massfraction': 0.0012576777529689648},
 'magnesium': {'abundance': 3.9810717055349695e-05,
  'massfraction': 0.0007085170384267315},
 'silicon': {'abundance': 3.235936569296281e-05,
  'massfraction': 0.0006654827968172229},
 'sulphur': {'abundance': 1.3182567385564074e-05,
  'massfraction': 0.00030951800499730997},
 'calcium': {'abundance': 2.1877616239495517e-06,
  'massfraction': 6.420379718268677e-05},
 'iron': {'abundance': 3.1622776601683795e-05,
  'massfraction': 0.0012931667271008657},
 

# additional information stored in sub-dictionaries

In [21]:
# dictionary of useful information about the simulation

part.info

{'particle.numbers.in.file': array([5969934, 8820344, 3081337,       0, 3059250,       0], dtype=int32),
 'particle.numbers.total': array([5969934, 8820344, 3081337,       0, 3059250,       0], dtype=uint32),
 'particle.numbers.total.high.word': array([0, 0, 0, 0, 0, 0], dtype=uint32),
 'particle.masses': array([0., 0., 0., 0., 0., 0.]),
 'redshift': 0.0,
 'box.length': 85470.08547008547,
 'file.number.per.snapshot': 1,
 'omega_matter': 0.272,
 'omega_lambda': 0.728,
 'hubble': 0.702,
 'has.star.formation': 1,
 'has.cooling': 1,
 'has.star.age': 1,
 'has.metals': 15,
 'has.feedback': 1,
 'has.double.precision': 0,
 'has.ic.info': 3,
 'compression.level': 0,
 'compression.readme': 'This snapshot is part of the Feedback in Realistic Environments (FIRE) project -- Use, modification, or distribution only permitted with approval of the PI and the FIRE team -- No warranty, use at your own risk -- compactify_hdf5 (c) RF 2018',
 'compression.version': 'v0.2',
 'is.cosmological': True,
 'scalef

In [22]:
# dictionary of information about this snapshot's index, scale-factor, redshift, time, lookback-time

part.snapshot

{'index': 600,
 'redshift': 0.0,
 'scalefactor': 1.0,
 'time': 13.798746882657936,
 'time.lookback': 0.0,
 'time.hubble': 13.928664125669}

In [23]:
# dictionary class of arrays about *all* snapshots that were saved for the simulation

print(part.Snapshot.keys())
print(part.Snapshot['redshift'][:10])

dict_keys(['index', 'scalefactor', 'redshift', 'time', 'time.width'])
[99.        19.        15.        14.605911  14.230769  13.8732395
 13.53211   13.206278  12.894737  12.596566 ]


In [24]:
# dictionary class of cosmological parameters, with function for cosmological conversions

part.Cosmology

{'omega_lambda': 0.728,
 'omega_matter': 0.272,
 'omega_baryon': 0.0455,
 'omega_curvature': 0.0,
 'omega_dm': 0.22650000000000003,
 'baryon.fraction': 0.16727941176470587,
 'hubble': 0.7020000000000001,
 'sigma_8': 0.807,
 'n_s': 0.961,
 'w': -1.0}

In [26]:
# position [kpc comoving] and velocity [km / s] of the center of each host galaxy
# this was computed and stored during read in
# can store multiple hosts, though usually just one

print(part.host_positions)
print(part.host_velocities)

[[41821.97367711 44122.00484177 46288.4484585 ]]
[[-48.737286  73.20827   96.66946 ]]


See gizmo.analysis for examples of high-level analysis, including plotting these data.

See ut.particle for mid-level analysis functions that may be useful.

See other modules within utilities for low-level functions that may be useful.

# principal axes of stellar disk

In [36]:
# compute and assign principal axes (defined via moment of inertia tensor) of stars during read in as below

part = gizmo.io.Read.read_snapshots(['star', 'dark'], 'redshift', 0, assign_host_principal_axes=True)


# in utilities.simulation.Snapshot():
  reading:  snapshot_times.txt
  input redshift = 0:  using snapshot index = 600, redshift = 0.000


# in gizmo_analysis.gizmo_io.Read():
* reading header from:  output/snapshot_600.hdf5
  snapshot contains the following number of particles:
    dark      (id = 1): 8820344 particles
    dark2     (id = 2): 3081337 particles
    gas       (id = 0): 5969934 particles
    star      (id = 4): 3059250 particles
    blackhole (id = 5): 0 particles

* reading species: ['star', 'dark']
* reading particles from:
    output/snapshot_600.hdf5

* reading cosmological parameters from:  initial_condition/ic_agora_m12i.conf

* checking sanity of particle properties

* assigning coordinates of host galaxy[s]/halo[s]:
  position = (41821.974, 44122.005, 46288.448) [kpc comoving]
  velocity = (-48.7, 73.2, 96.7) [km / s]

* assigning principal axes of host galaxy[s]/halo[s]:
  using star particles at distance < 15 kpc
  using distances that encloses 90% of mass
  u

In [39]:
# rotation tensors of principal axes for each host are stored via

print(part.host_rotation_tensors[0])

[[ 0.20397335  0.45612521  0.86622437]
 [ 0.8729429   0.31577278 -0.37183093]
 [-0.44313154  0.83200802 -0.33376204]]


In [40]:
# now can compute different types of distance of star particle from center of host galaxy
# compute 3-D distance from host galaxy center along simulation's default x,y,z cartesian axes [kpc physical]

part['star'].prop('host.distance')

array([[ 1268.83208172,  5564.34890325, -4928.10562341],
       [ 3106.31973213,  2376.85209351, -4314.64238128],
       [ 2343.09614995,  1783.56843904,   860.76900457],
       ...,
       [  137.22019795, -1574.3404895 ,  -179.61490314],
       [  137.33256157, -1574.5766965 ,  -179.46876353],
       [  137.33369847, -1574.91948576,  -179.89308991]])

In [41]:
# compute total (scalar) distance

part['star'].prop('host.distance.total')

array([7540.43358198, 5823.640359  , 3067.92099375, ..., 1590.48384872,
       1590.71086081, 1591.09819155])

In [42]:
# compute 3-D distance aligned with the principal (major, intermediate, minor) axes

part['star'].prop('host.distance.principal')

array([[-1471.99745052,  4697.1099597 ,  5712.13796546],
       [-2019.69978771,  5066.5024369 ,  2041.11559089],
       [ 2037.07879133,  2288.53098007,   158.35142894],
       ...,
       [ -845.6939332 ,  -310.56209532, -1310.72187337],
       [ -845.65216429,  -310.59293526, -1311.01696721],
       [ -846.17584907,  -310.54240865, -1311.16105038]])

In [43]:
# compute 3-D distance aligned with the principal axes in cylindrical coordinates
# first value is along the major axes (R, positive definite)
# second value is vertical height wrt the disk (Z, signed)
# third value is angle (phi, 0 to 2 * pi)

part['star'].prop('host.distance.principal.cylindrical')

array([[ 4.92235903e+03,  5.71213797e+03,  1.87448602e+00],
       [ 5.45423085e+03,  2.04111559e+03,  1.95012791e+00],
       [ 3.06383160e+03,  1.58351429e+02,  8.43463855e-01],
       ...,
       [ 9.00914560e+02, -1.31072187e+03,  3.49353175e+00],
       [ 9.00885983e+02, -1.31101697e+03,  3.49357987e+00],
       [ 9.01360169e+02, -1.31116105e+03,  3.49332695e+00]])

In [44]:
# same for velocity
# compute 3-D velocity from host galaxy center along simulation's default x,y,z cartesian axes [km / s]

part['star'].prop('host.velocity')

array([[ 153.69781  ,  682.3818   , -596.6675   ],
       [ 439.40842  ,  148.70575  , -766.1859   ],
       [ 339.27658  ,   43.9933   ,   84.86846  ],
       ...,
       [   3.8416476,  -90.69804  , -134.58772  ],
       [   6.3950295, -152.07191  , -133.20901  ],
       [ -22.332697 ,  -87.4856   , -117.72802  ]], dtype=float32)

In [45]:
# compute total (scalar) velocity [km / s]

part['star'].prop('host.velocity.total')

array([919.3911 , 895.6752 , 352.48642, ..., 162.34145, 202.26569,
       148.36565], dtype=float32)

In [46]:
# compute 3-D velocity along the principal (major, intermediate, minor) axes [km / s]

part['star'].prop('host.velocity.principal')

array([[-174.24612  ,  571.5064   ,  698.7837   ],
       [-506.23285  ,  715.4273   ,  184.73242  ],
       [ 162.78496  ,  278.50424  , -142.06725  ],
       ...,
       [-157.16924  ,   24.757446 ,  -32.243576 ],
       [-183.44832  ,    7.0935564,  -84.89878  ],
       [-146.43854  ,   -3.3458223,  -23.599258 ]], dtype=float32)

In [47]:
# compute 3-D velocity in cylindrical coordinates
# first value is along the major axes (positive definite)
# second value is vertical velocity wrt the disk (signed)
# third value is azimuthal velocity in the plane of the disk (positive definite)

part['star'].prop('host.velocity.principal.cylindrical')

array([[ 597.4611   ,  698.7837   ,   -4.6324883],
       [ 852.0271   ,  184.73242  ,  205.32347  ],
       [ 316.2613   , -142.06725  ,   63.57943  ],
       ...,
       [ 139.00136  ,  -32.243576 ,  -77.419136 ],
       [ 169.7554   ,  -84.89878  ,  -69.905    ],
       [ 138.6258   ,  -23.599258 ,  -47.310966 ]], dtype=float32)

# particle tracking

Some simulations have pre-compiled HDF5 files to help with star particle tracking. These are stored in the directory 'track/' (if present). The code that generates and reads these files is in gizmo_track.py.

star\_indices\_*.hdf5 files store, for each star particles at z = 0, a pointer to where it was in the catalog at each previous snapshot (replace * with snapshot index). This makes it easy to quickly get the properties of a given star particle at any previous snapshot. These pointers are stored in an HDF5 file, one for each previous snapshot.

In [48]:
# first, read catalog of star particles at z = 0

part_at_z0 = gizmo.io.Read.read_snapshots(['star'], 'redshift', 0)


# in utilities.simulation.Snapshot():
  reading:  snapshot_times.txt
  input redshift = 0:  using snapshot index = 600, redshift = 0.000


# in gizmo_analysis.gizmo_io.Read():
* reading header from:  output/snapshot_600.hdf5
  snapshot contains the following number of particles:
    dark      (id = 1): 8820344 particles
    dark2     (id = 2): 3081337 particles
    gas       (id = 0): 5969934 particles
    star      (id = 4): 3059250 particles
    blackhole (id = 5): 0 particles

* reading species: ['star']
* reading particles from:
    output/snapshot_600.hdf5

* reading cosmological parameters from:  initial_condition/ic_agora_m12i.conf

* checking sanity of particle properties

* assigning coordinates of host galaxy[s]/halo[s]:
  position = (41821.974, 44122.005, 46288.448) [kpc comoving]
  velocity = (-48.7, 73.2, 96.7) [km / s]



In [49]:
# say that you want to find out what they were doing at z = 1
# read in catalog of star particles at z = 1 (snapshot 277)

part_at_z1 = gizmo.io.Read.read_snapshots(['star'], 'redshift', 1)


# in utilities.simulation.Snapshot():
  reading:  snapshot_times.txt
  input redshift = 1:  using snapshot index = 277, redshift = 1.000


# in gizmo_analysis.gizmo_io.Read():
* reading header from:  output/snapshot_277.hdf5
  snapshot contains the following number of particles:
    dark      (id = 1): 8820344 particles
    dark2     (id = 2): 3081337 particles
    gas       (id = 0): 7498674 particles
    star      (id = 4): 1333580 particles
    blackhole (id = 5): 0 particles

* reading species: ['star']
* reading particles from:
    output/snapshot_277.hdf5

* reading cosmological parameters from:  initial_condition/ic_agora_m12i.conf

* checking sanity of particle properties

* assigning coordinates of host galaxy[s]/halo[s]:
  position = (42434.347, 43258.424, 45265.678) [kpc comoving]
  velocity = (-62.5, 90.3, 88.6) [km / s]



In [50]:
# use the function within gizmo_track.py to read star index pointers associated with the catalog z = 1

gizmo.track.ParticleIndexPointer.io_pointers(part_at_z1)


# in utilities.basic.io.file_hdf5():
  read file: star_indices_277.hdf5
    indices | int32, shape = (3059250,)


In [51]:
# pointers are stored via numpy array appended to particle dictionary at the relevant snapshot
# a negative value means that the star formed after this snapshot (so it does not exist at this snapshot)

part_at_z1.index_pointers

array([  323940, -3059251,    74555, ..., -3059251,   988214,  1016593],
      dtype=int32)

In [52]:
# so, say that you have a list of the indices of star particles of interest at z = 0

indices_at_z0 = np.array([2, 5, 8, 13])

In [53]:
# their positions at z = 0

part_at_z0['star']['position'][indices_at_z0]

array([[44165.06982706, 45905.57328081, 47149.21746307],
       [43395.66430266, 44225.91487342, 46848.42028784],
       [43391.32501013, 44235.3333939 , 46851.26898524],
       [43392.7246372 , 44234.88455716, 46860.08437896]])

In [54]:
# get their indices in the catalog at z = 1

indices_at_z1 = part_at_z1.index_pointers[indices_at_z0]
print(indices_at_z1)

[ 74555 380059 380069 387683]


In [55]:
# now you easily can get any property of interest at z = 1, for example, positions

part_at_z1['star']['position'][indices_at_z1]

array([[43138.89641753, 45843.089133  , 45802.62793454],
       [44182.77201273, 43321.63152774, 46024.87924174],
       [44196.26418051, 43329.33473156, 46025.0469051 ],
       [44180.96240584, 43316.70104104, 46032.82963564]])

Another useful file: star\_form\_coordinates\_600.hdf5 stores, for each star particle at z = 0, its 3-D distance and 3-D velocity wrt to the main host galaxy at the first snapshot after it formed. These coordinates are aligned with the principal (major, intermediate, minor) axes of the stellar disk (as defined via its moment of inertia tensor) at that snapshot.

In [56]:
# use the function within gizmo_track.py to read this file and assign values directly to the catalog at z = 0

gizmo.track.ParticleCoordinate.io_formation_coordinates(part_at_z0)


# in utilities.basic.io.file_hdf5():
  read file: star_form_coordinates_600.hdf5
    center.position | float32, shape = (601, 3)
    center.velocity | float32, shape = (601, 3)
    form.host.distance | float32, shape = (3059250, 3)
    form.host.velocity | float32, shape = (3059250, 3)
    id | uint32, shape = (3059250,)
    principal.axes.vectors | float32, shape = (601, 3, 3)


In [57]:
# alternately, you can read the formation coordinates at the same time read snapshot itself

part_at_z0 = gizmo.io.Read.read_snapshots(
    ['star'], 'redshift', 0, assign_host_principal_axes=True, assign_formation_coordinates=True)


# in utilities.simulation.Snapshot():
  reading:  snapshot_times.txt
  input redshift = 0:  using snapshot index = 600, redshift = 0.000


# in gizmo_analysis.gizmo_io.Read():
* reading header from:  output/snapshot_600.hdf5
  snapshot contains the following number of particles:
    dark      (id = 1): 8820344 particles
    dark2     (id = 2): 3081337 particles
    gas       (id = 0): 5969934 particles
    star      (id = 4): 3059250 particles
    blackhole (id = 5): 0 particles

* reading species: ['star']
* reading particles from:
    output/snapshot_600.hdf5

* reading cosmological parameters from:  initial_condition/ic_agora_m12i.conf

* checking sanity of particle properties

* assigning coordinates of host galaxy[s]/halo[s]:
  position = (41821.974, 44122.005, 46288.448) [kpc comoving]
  velocity = (-48.7, 73.2, 96.7) [km / s]

* assigning principal axes of host galaxy[s]/halo[s]:
  using star particles at distance < 15 kpc
  using distances that encloses 90% of mass
  using you

In [58]:
# 3-D distance at formation, aligned with the principal axes of the host galaxy at that time [kpc physical]
# principal axes defined according to all star particles within the host galaxy, independently at each snapshot
# distance along dimension 0 is aligned with the major axis
# distance along dimension 1 is algined with the intermediate axis
# distance along dimension 2 is aligned with the minor (Z) axis

part_at_z0['star']['form.host.distance']

array([[    3.8351834,     6.170289 ,    -1.4488623],
       [  951.6061   , -1143.819    ,   541.5925   ],
       [ 1258.5391   ,   183.60645  ,   -92.80096  ],
       ...,
       [  542.5843   ,  -580.9797   ,   927.32684  ],
       [ -376.8372   ,   349.8039   ,  -245.89764  ],
       [ -275.3792   ,   -35.97139  ,  -272.96063  ]], dtype=float32)

In [59]:
# total scalar (absolute) distance wrt the host galaxy at formation [kpc physical]
# this is a derived quantity, so need to call via .prop()

part_at_z0['star'].prop('form.host.distance.total')

array([   7.408124, 1583.4136  , 1275.2427  , ..., 1221.4214  ,
        569.9427  ,  389.4036  ], dtype=float32)

In [60]:
# 3-D distance at formation wrt the host galaxy in cylindrical coordinates [kpc physical]

part_at_z0['star'].prop('form.host.distance.cylindrical')

array([[ 7.2650599e+00, -1.4488623e+00,  1.0146770e+00],
       [ 1.4879099e+03,  5.4159253e+02,  5.4063134e+00],
       [ 1.2718616e+03, -9.2800957e+01,  1.4486657e-01],
       ...,
       [ 7.9494348e+02,  9.2732684e+02,  5.4636278e+00],
       [ 5.1416827e+02, -2.4589764e+02,  2.3933804e+00],
       [ 2.7771866e+02, -2.7296063e+02,  3.2714822e+00]], dtype=float32)

In [61]:
# these value look more reasonable if restrict to star particles that formed within the host galaxy

# select particles formed at d = 0 - 8 kpc physical
part_indices = ut.array.get_indices(part_at_z0['star'].prop('form.host.distance.total'), [0, 8])

part_at_z0['star'].prop('form.host.distance.cylindrical', part_indices)

array([[ 7.26506   , -1.4488623 ,  1.014677  ],
       [ 2.819624  , -0.01174179,  4.65897   ],
       [ 2.4207215 , -0.02199288,  3.6387615 ],
       ...,
       [ 2.7438505 , -1.4894025 ,  5.987568  ],
       [ 3.6302092 , -0.01234316,  3.3655412 ],
       [ 1.5276729 , -0.12618025,  1.8085258 ]], dtype=float32)

# profile of property

A common task is to compute a radial profile of a given quantity, such as mass density, average age, median metallicity, etc.

The high-level functions below make this easier to do.

In [74]:
# first, initiate an instance of SpeciesProfileClass
# as you initialize,choose your distance/radius binning scheme: 
#   'log' v 'linear', distance limits, bin width, number of spatial dimensions of profile
# refer to ut.binning.DistanceBinClass() for more

# linear binning from 0 to 20 kpc with 1 kpc bin width, assuming a 3-D profile
SpeciesProfile = ut.particle.SpeciesProfileClass(scaling='linear', limits=[0, 20], width=1, dimension_number=3)

In [75]:
# using this binning scheme,
# compute sum/histogram/density of mass of star particles in each bin
# this returns a bunch of summed properties via a dictionary

pro = SpeciesProfile.get_sum_profiles(part, 'star', 'mass')


# in utilities.particle.SpeciesProfile():
  input  3059250 distances -  2706222 (88.5%) are within limits = [0.000, 20.000]


In [76]:
# in principle, you can supply a list of multiple species, and it will compute profiles for each
# thus, it returns a dictionary for each species

pro.keys()

dict_keys(['star', 'baryon', 'total'])

In [77]:
# the quantities that it stores in each bin

pro['star'].keys()

dict_keys(['sum', 'sum.cum', 'log sum', 'log sum.cum', 'density', 'log density', 'density.cum', 'log density.cum', 'density*r', 'log density*r', 'density*r^2', 'log density*r^2', 'distance.mid', 'distance.cum', 'log distance.mid', 'log distance.cum', 'sum.fraction', 'sum.cum.fraction', 'vel.circ'])

In [78]:
# alternately, you may want to compute profiles along a disks R or Z axes
# if so, first define the dimensionality of the profile when you initiate the class

# log binning from 0.1 to 10 kpc with 0.1 dex bin width, assuming a 2-D profile (along R)
SpeciesProfile = ut.particle.SpeciesProfileClass(scaling='log', limits=[0.1, 10], width=0.1, dimension_number=2)

In [79]:
# set rotation = True to force it to compute profiles along the principal axes (assuming that you read them in)
# use other_axis_distance_limits to limit the extent along the other axis, 
#   in this case, limit the Z axis to within +/- 1 kpc (in the profile, all distances are absolute)

pro = SpeciesProfile.get_sum_profiles(part, 'star', 'mass', rotation=True, other_axis_distance_limits=[0, 1])


# in utilities.particle.SpeciesProfile():
  input  2097104 distances -  2064147 (98.4%) are within limits = [0.100, 10.000]


In [80]:
# similarly, do this to compute profiles along Z

# log binning from 0.1 to 10 kpc with 0.1 dex bin width, assuming a 1-D profile (along Z)
SpeciesProfile = ut.particle.SpeciesProfileClass(scaling='log', limits=[0.1, 10], width=0.1, dimension_number=1)

# limit the R axex to [5, 8] kpc 
pro = SpeciesProfile.get_sum_profiles(part, 'star', 'mass', rotation=True, other_axis_distance_limits=[5, 8])


# in utilities.particle.SpeciesProfile():
  input   293249 distances -   259651 (88.5%) are within limits = [0.100, 10.000]


In [81]:
# using the same binning scheme
# this function computes various statistics of a property of star particles in each bin
# by default, it weights the property by the mass of each particle
# this returns a bunch of statistics via a dictionary

pro = SpeciesProfile.get_statistics_profiles(
    part, 'star', 'age', weight_by_mass=True, rotation=True, other_axis_distance_limits=[5, 8])

  input   293249 distances -   259651 (88.5%) are within limits = [0.100, 10.000]


In [82]:
# the quantities that it stores in each bin

pro['star'].keys()

dict_keys(['limits', 'number', 'median', 'percent.16', 'percent.84', 'percent.2', 'percent.98', 'percent.0.1', 'percent.99.9', 'percent.25', 'percent.75', 'percents.68', 'percents.95', 'median.dif.2', 'median.dif.16', 'median.dif.84', 'median.dif.98', 'median.difs.68', 'median.difs.95', 'average', 'std', 'sem', 'std.lo', 'std.hi', 'min', 'max', 'percent.50', 'average.50', 'sem.lo', 'sem.hi', 'distance.mid', 'distance.cum', 'log distance.mid', 'log distance.cum'])